In [1]:
import pandas as pd
import json
import numpy as np

In [2]:
with open("../data/raw_data/competitions.json", "r") as f:
    data = json.load(f)
data[0]

{'competition_id': 9,
 'season_id': 281,
 'country_name': 'Germany',
 'competition_name': '1. Bundesliga',
 'competition_gender': 'male',
 'competition_youth': False,
 'competition_international': False,
 'season_name': '2023/2024',
 'match_updated': '2024-09-28T20:46:38.893391',
 'match_updated_360': '2025-07-06T04:26:07.636270',
 'match_available_360': '2025-07-06T04:26:07.636270',
 'match_available': '2024-09-28T20:46:38.893391'}

In [3]:
comp_list = []
for i in range(len(data)):
    comp_dict = {}
    comp_dict["competition_id"] = data[i]["competition_id"]
    comp_dict["competition_name"] = data[i]["competition_name"]
    comp_dict["country_name"] = data[i]["country_name"]
    comp_list.append(comp_dict)
comp_list[:10]

[{'competition_id': 9,
  'competition_name': '1. Bundesliga',
  'country_name': 'Germany'},
 {'competition_id': 9,
  'competition_name': '1. Bundesliga',
  'country_name': 'Germany'},
 {'competition_id': 1267,
  'competition_name': 'African Cup of Nations',
  'country_name': 'Africa'},
 {'competition_id': 16,
  'competition_name': 'Champions League',
  'country_name': 'Europe'},
 {'competition_id': 16,
  'competition_name': 'Champions League',
  'country_name': 'Europe'},
 {'competition_id': 16,
  'competition_name': 'Champions League',
  'country_name': 'Europe'},
 {'competition_id': 16,
  'competition_name': 'Champions League',
  'country_name': 'Europe'},
 {'competition_id': 16,
  'competition_name': 'Champions League',
  'country_name': 'Europe'},
 {'competition_id': 16,
  'competition_name': 'Champions League',
  'country_name': 'Europe'},
 {'competition_id': 16,
  'competition_name': 'Champions League',
  'country_name': 'Europe'}]

In [4]:
comp_data = pd.DataFrame(comp_list)
comp_data.head()

   competition_id        competition_name country_name
0               9           1. Bundesliga      Germany
1               9           1. Bundesliga      Germany
2            1267  African Cup of Nations       Africa
3              16        Champions League       Europe
4              16        Champions League       Europe

In [5]:
comp_data["competition_name"] = comp_data["competition_name"].str.replace(r"^\d+\.\s*", "", regex=True)
comp_data.head()

   competition_id        competition_name country_name
0               9              Bundesliga      Germany
1               9              Bundesliga      Germany
2            1267  African Cup of Nations       Africa
3              16        Champions League       Europe
4              16        Champions League       Europe

In [6]:
seasons_list = []
for i in range(len(data)):
    seasons_dict = {}
    seasons_dict["season_id"] = data[i]["season_id"]
    seasons_dict["season_name"] = data[i]["season_name"]
    seasons_dict["competition_id"] = data[i]["competition_id"]
    seasons_list.append(seasons_dict)
seasons_list[:10]

[{'season_id': 281, 'season_name': '2023/2024', 'competition_id': 9},
 {'season_id': 27, 'season_name': '2015/2016', 'competition_id': 9},
 {'season_id': 107, 'season_name': '2023', 'competition_id': 1267},
 {'season_id': 4, 'season_name': '2018/2019', 'competition_id': 16},
 {'season_id': 1, 'season_name': '2017/2018', 'competition_id': 16},
 {'season_id': 2, 'season_name': '2016/2017', 'competition_id': 16},
 {'season_id': 27, 'season_name': '2015/2016', 'competition_id': 16},
 {'season_id': 26, 'season_name': '2014/2015', 'competition_id': 16},
 {'season_id': 25, 'season_name': '2013/2014', 'competition_id': 16},
 {'season_id': 24, 'season_name': '2012/2013', 'competition_id': 16}]

In [7]:
seasons_data = pd.DataFrame(seasons_list)
seasons_data.head()

   season_id season_name  competition_id
0        281   2023/2024               9
1         27   2015/2016               9
2        107        2023            1267
3          4   2018/2019              16
4          1   2017/2018              16

In [8]:
seasons_data = seasons_data.drop_duplicates(subset=["season_id"])
comp_data = comp_data.drop_duplicates(subset=["competition_id"])
seasons_data.head()

   season_id season_name  competition_id
0        281   2023/2024               9
1         27   2015/2016               9
2        107        2023            1267
3          4   2018/2019              16
4          1   2017/2018              16

In [9]:
comp_data.head()

    competition_id        competition_name   country_name
0                9              Bundesliga        Germany
2             1267  African Cup of Nations         Africa
3               16        Champions League         Europe
21             223            Copa America  South America
22              87            Copa del Rey          Spain

In [11]:
print(comp_data["competition_id"].is_unique)
print(seasons_data["season_id"].is_unique)

True
True