In [ ]:
!pip install sqlalchemy pymysql jupysql

In [1]:
from pathlib import Path
import json
import pandas as pd

from getpass import getpass
from sqlalchemy import URL, create_engine, text

In [2]:
password = getpass("Enter your MYSQL password: ")

connection_url = URL.create(drivername="mysql+pymysql", username="notebook_user", password=password, host="localhost", port=3306, database="football_db")

engine = create_engine(connection_url)

Enter your MYSQL password:  ········

In [3]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT DATABASE();"))
    print(result.fetchone())

('football_db',)

In [4]:
%load_ext sql
%sql engine

In [5]:
%%sql

create table if not exists countries(
    country_id int primary key,
    country_name varchar(255) not null
);

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

++
||
++
++

In [6]:
%%sql 
select * from countries;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

+------------+--------------+
| country_id | country_name |
+------------+--------------+
+------------+--------------+

In [7]:
%%sql

create table if not exists teams(
    team_id int primary key,
    team_name varchar(255) not null
);

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

++
||
++
++

In [8]:
%%sql

create table if not exists players (
    player_id int primary key,
    player_name varchar(255) not null,
    country_id int,
    
    foreign key (country_id) references countries(country_id)
);

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

++
||
++
++

In [9]:
%%sql

create table if not exists competitions (
    competition_id int primary key,
    competition_name varchar(255),
    country_name varchar(255)
);

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

++
||
++
++

In [10]:
%%sql

create table if not exists seasons (
    season_id int primary key,
    season_name varchar(255),
    competition_id int,

    foreign key (competition_id) references competitions(competition_id)
);

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

++
||
++
++

In [11]:
%%sql

create table if not exists matches (
    match_id int primary key,
    match_date date,
    match_week int,
    home_score int,
    away_score int,
    home_team_id int,
    away_team_id int,
    competition_id int,
    season_id int,
    competition_stage int,
    
    foreign key (competition_id) references competitions(competition_id),
    foreign key (season_id) references seasons(season_id),
    foreign key (home_team_id) references teams(team_id),
    foreign key (away_team_id) references teams(team_id)
);

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

++
||
++
++

In [12]:
%%sql

create table if not exists lineups (
    match_id int,
    team_id int,
    player_id int,
    jersey_number int,

    primary key (match_id, player_id),

    foreign key (match_id) references matches(match_id),
    foreign key (team_id) references teams(team_id),
    foreign key (player_id) references players(player_id)
);

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

++
||
++
++

In [13]:
%%sql
describe matches

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

10 rows affected.

+-------------------+------+------+-----+---------+-------+
|       Field       | Type | Null | Key | Default | Extra |
+-------------------+------+------+-----+---------+-------+
|      match_id     | int  |  NO  | PRI |   None  |       |
|     match_date    | date | YES  |     |   None  |       |
|     match_week    | int  | YES  |     |   None  |       |
|     home_score    | int  | YES  |     |   None  |       |
|     away_score    | int  | YES  |     |   None  |       |
|    home_team_id   | int  | YES  | MUL |   None  |       |
|    away_team_id   | int  | YES  | MUL |   None  |       |
|   competition_id  | int  | YES  | MUL |   None  |       |
|     season_id     | int  | YES  | MUL |   None  |       |
| competition_stage | int  | YES  |     |   None  |       |
+-------------------+------+------+-----+---------+-------+
Truncated to displaylimit of 10.

In [5]:
%%sql

SHOW TABLES;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

8 rows affected.

+-----------------------+
| Tables_in_football_db |
+-----------------------+
|      competitions     |
|       countries       |
|         events        |
|        lineups        |
|        matches        |
|        players        |
|        seasons        |
|         teams         |
+-----------------------+

In [15]:
%%sql

SELECT COUNT(*) AS teams_count FROM teams;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+-------------+
| teams_count |
+-------------+
|     312     |
+-------------+

In [16]:
%%sql

SELECT COUNT(*) AS matches_count FROM matches;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+---------------+
| matches_count |
+---------------+
|      3464     |
+---------------+

In [17]:
%%sql

SELECT COUNT(*) AS lineups_count FROM lineups;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+---------------+
| lineups_count |
+---------------+
|       0       |
+---------------+

In [ ]:
# %%sql

# insert into competitions (
#     competition_id,
#     competition_name,
#     country_name
# )
# values (
#     9,
#     'Bundesliga',
#     'Germany'
# );

In [18]:
%%sql

select * from competitions;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

21 rows affected.

+----------------+-------------------------+--------------------------+
| competition_id |     competition_name    |       country_name       |
+----------------+-------------------------+--------------------------+
|       2        |      Premier League     |         England          |
|       7        |         Ligue 1         |          France          |
|       9        |        Bundesliga       |         Germany          |
|       11       |         La Liga         |          Spain           |
|       12       |         Serie A         |          Italy           |
|       16       |     Champions League    |          Europe          |
|       35       |    UEFA Europa League   |          Europe          |
|       37       | FA Women's Super League |         England          |
|       43       |      FIFA World Cup     |      International       |
|       44       |   Major League Soccer   | United States of America |
+----------------+-------------------------+--------------------------+
Truncated to displaylimit of 10.

In [19]:
%%sql

select count(*) from competitions;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+----------+
| count(*) |
+----------+
|    21    |
+----------+

In [20]:
with open("../data/raw_data/competitions.json", "r") as f:
    comp_data = json.load(f)

comp_list = []

for data in comp_data:
    comp_dict = {}
    comp_dict["competition_id"] = data["competition_id"]
    comp_dict["competition_name"] = data["competition_name"]
    comp_dict["country_name"] = data["country_name"]
    comp_list.append(comp_dict)

comp_df = pd.DataFrame(comp_list)
comp_df["competition_name"] = comp_df["competition_name"].str.replace(r"^\d+\.\s*", "", regex=True).reset_index(drop=True)
comp_df = comp_df.drop_duplicates(subset=["competition_id"])
comp_df.head()

    competition_id        competition_name   country_name
0                9              Bundesliga        Germany
2             1267  African Cup of Nations         Africa
3               16        Champions League         Europe
21             223            Copa America  South America
22              87            Copa del Rey          Spain

In [21]:
print(comp_df["competition_id"].is_unique)

True

In [ ]:
comp_df.to_sql(name='competitions', con=engine, if_exists="append", index=False)

In [22]:
%%sql

select * from competitions limit 5;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

5 rows affected.

+----------------+------------------+--------------+
| competition_id | competition_name | country_name |
+----------------+------------------+--------------+
|       2        |  Premier League  |   England    |
|       7        |     Ligue 1      |    France    |
|       9        |    Bundesliga    |   Germany    |
|       11       |     La Liga      |    Spain     |
|       12       |     Serie A      |    Italy     |
+----------------+------------------+--------------+

In [23]:
%%sql

select count(*) from competitions;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+----------+
| count(*) |
+----------+
|    21    |
+----------+

In [24]:
seasons_list = []

for data in comp_data:
    seasons_dict = {}
    seasons_dict["season_id"] = data["season_id"]
    seasons_dict["season_name"] = data["season_name"]
    seasons_dict["competition_id"] = data["competition_id"]
    seasons_list.append(seasons_dict)

seasons_df = pd.DataFrame(seasons_list)
seasons_df = seasons_df.drop_duplicates(subset=["season_id"]).reset_index(drop=True)
seasons_df.head()

   season_id season_name  competition_id
0        281   2023/2024               9
1         27   2015/2016               9
2        107        2023            1267
3          4   2018/2019              16
4          1   2017/2018              16

In [ ]:
seasons_df.to_sql(name='seasons', con=engine, if_exists="append", index=False)

In [25]:
%%sql

select * from seasons limit 5;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

5 rows affected.

+-----------+-------------+----------------+
| season_id | season_name | competition_id |
+-----------+-------------+----------------+
|     1     |  2017/2018  |       16       |
|     2     |  2016/2017  |       16       |
|     3     |     2018    |       43       |
|     4     |  2018/2019  |       16       |
|     21    |  2009/2010  |       16       |
+-----------+-------------+----------------+

In [26]:
%%sql

select count(*) from seasons;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+----------+
| count(*) |
+----------+
|    48    |
+----------+

In [27]:
%%sql

select competition_name, country_name from competitions;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

21 rows affected.

+-------------------------+--------------------------+
|     competition_name    |       country_name       |
+-------------------------+--------------------------+
|      Premier League     |         England          |
|         Ligue 1         |          France          |
|        Bundesliga       |         Germany          |
|         La Liga         |          Spain           |
|         Serie A         |          Italy           |
|     Champions League    |          Europe          |
|    UEFA Europa League   |          Europe          |
| FA Women's Super League |         England          |
|      FIFA World Cup     |      International       |
|   Major League Soccer   | United States of America |
+-------------------------+--------------------------+
Truncated to displaylimit of 10.

In [28]:
%%sql

select season_name, competition_id from seasons;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

48 rows affected.

+-------------+----------------+
| season_name | competition_id |
+-------------+----------------+
|  2017/2018  |       16       |
|  2016/2017  |       16       |
|     2018    |       43       |
|  2018/2019  |       16       |
|  2009/2010  |       16       |
|  2010/2011  |       16       |
|  2011/2012  |       16       |
|  2012/2013  |       16       |
|  2013/2014  |       16       |
|  2014/2015  |       16       |
+-------------+----------------+
Truncated to displaylimit of 10.

In [29]:
%%sql

select * from competitions where country_name = 'England';

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

2 rows affected.

+----------------+-------------------------+--------------+
| competition_id |     competition_name    | country_name |
+----------------+-------------------------+--------------+
|       2        |      Premier League     |   England    |
|       37       | FA Women's Super League |   England    |
+----------------+-------------------------+--------------+

In [30]:
%%sql

select * from seasons where competition_id = 9;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

2 rows affected.

+-----------+-------------+----------------+
| season_id | season_name | competition_id |
+-----------+-------------+----------------+
|     27    |  2015/2016  |       9        |
|    281    |  2023/2024  |       9        |
+-----------+-------------+----------------+

In [31]:
%%sql

select season_id, season_name from seasons where competition_id = 9

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

2 rows affected.

+-----------+-------------+
| season_id | season_name |
+-----------+-------------+
|     27    |  2015/2016  |
|    281    |  2023/2024  |
+-----------+-------------+

In [32]:
%%sql 

delete from teams;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

RuntimeError: (pymysql.err.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`football_db`.`matches`, CONSTRAINT `matches_ibfk_3` FOREIGN KEY (`home_team_id`) REFERENCES `teams` (`team_id`))')
[SQL: delete from teams;]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [33]:
matches_dir = Path('../data/raw_data/matches')
match_files = matches_dir.rglob('*.json')

teams_list = []

for file in match_files:
    with open(file, 'r') as f:
        match_data = json.load(f)

        for data in match_data:
            home_team = {
            "team_id": data["home_team"]["home_team_id"],
            "team_name": data["home_team"]["home_team_name"],
            }

            away_team = {
            "team_id": data["away_team"]["away_team_id"],
            "team_name": data["away_team"]["away_team_name"],
            }

            teams_list.append(home_team)
            teams_list.append(away_team)

teams_df = pd.DataFrame(teams_list)
teams_df = teams_df.drop_duplicates(subset=["team_id"]).reset_index(drop=True)
teams_df.head()

   team_id      team_name
0      775        Nigeria
1     3374  Côte d'Ivoire
2     4976   South Africa
3     4881       Congo DR
4      787        Senegal

In [51]:
teams_df.to_sql(name="teams", con=engine, if_exists="append", index=False)

312

In [34]:
%%sql

select * from teams limit 10;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

10 rows affected.

+---------+----------------------+
| team_id |      team_name       |
+---------+----------------------+
|    1    |       Arsenal        |
|    22   |    Leicester City    |
|    23   |       Watford        |
|    24   |      Liverpool       |
|    25   |     Southampton      |
|    26   |     Swansea City     |
|    27   | West Bromwich Albion |
|    28   |   AFC Bournemouth    |
|    29   |       Everton        |
|    30   |      Stoke City      |
+---------+----------------------+
Truncated to displaylimit of 10.

In [35]:
%%sql

select * from teams where team_name like '%United%'

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

9 rows affected.

+---------+-----------------------+
| team_id |       team_name       |
+---------+-----------------------+
|    37   |    Newcastle United   |
|    39   |   Manchester United   |
|    40   |    West Ham United    |
|   101   |      Leeds United     |
|   972   |  West Ham United LFC  |
|   1214  | United States Women's |
|   1475  |   Manchester United   |
|   1839  |     United States     |
|   7285  |    NorthEast United   |
+---------+-----------------------+

In [36]:
match_files = list(matches_dir.glob("*/*.json"))
matches_list = []

for file in match_files:
    with open(file, 'r') as f:
        match_data = json.load(f)

        for data in match_data:
            match_dict = {}
            match_dict["match_id"] = data["match_id"]
            match_dict["match_date"] = data["match_date"]
            match_dict["match_week"] = data["match_week"]
            match_dict["home_score"] = data["home_score"]
            match_dict["away_score"] = data["away_score"]
            match_dict["home_team_id"] = data["home_team"]["home_team_id"]
            match_dict["away_team_id"] = data["away_team"]["away_team_id"]
            match_dict["competition_id"] = data["competition"]["competition_id"]
            match_dict["season_id"] = data["season"]["season_id"]
            match_dict["competition_stage"] = data["competition_stage"]["id"]
            
            matches_list.append(match_dict)

matches_df = pd.DataFrame(matches_list).reset_index(drop=True)
matches_df.head()

,match_id,match_date,match_week,home_score,away_score,home_team_id,away_team_id,competition_id,season_id,competition_stage
0,3923881,2024-02-11,8,1,2,775,3374,1267,107,26
1,3923880,2024-02-10,7,0,0,4976,4881,1267,107,25
2,3922838,2024-02-07,6,1,0,3374,4881,1267,107,15
3,3922837,2024-02-07,6,1,1,775,4976,1267,107,15
4,3922242,2024-01-29,4,1,1,787,3374,1267,107,33

In [55]:
matches_df.to_sql(name="matches", con=engine, if_exists="append", index=False)

3464

In [37]:
%%sql

select * from matches limit 10;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

10 rows affected.

+----------+------------+------------+------------+------------+--------------+--------------+----------------+-----------+-------------------+
| match_id | match_date | match_week | home_score | away_score | home_team_id | away_team_id | competition_id | season_id | competition_stage |
+----------+------------+------------+------------+------------+--------------+--------------+----------------+-----------+-------------------+
|   7298   | 2018-02-24 |     0      |     2      |     2      |     746      |     971      |       37       |     4     |         1         |
|   7430   | 2018-04-15 |     3      |     2      |     4      |     759      |     766      |       49       |     3     |         1         |
|   7443   | 2018-05-05 |     6      |     2      |     3      |     765      |     760      |       49       |     3     |         1         |
|   7444   | 2018-05-06 |     6      |     1      |     1      |     766      |     761      |       49       |     3     |         1         |
|   7445   | 2018-05-06 |     6      |     2      |     0      |     767      |     759      |       49       |     3     |         1         |
|   7451   | 2018-05-13 |     7      |     1      |     0      |     766      |     759      |       49       |     3     |         1         |
|   7456   | 2018-05-20 |     6      |     1      |     2      |     763      |     766      |       49       |     3     |         1         |
|   7457   | 2018-05-24 |     9      |     3      |     4      |     764      |     766      |       49       |     3     |         1         |
|   7471   | 2018-06-30 |     15     |     0      |     3      |     764      |     766      |       49       |     3     |         1         |
|   7472   | 2018-07-01 |     13     |     1      |     0      |     760      |     765      |       49       |     3     |         1         |
+----------+------------+------------+------------+------------+--------------+--------------+----------------+-----------+-------------------+
Truncated to displaylimit of 10.

In [38]:
%%sql

select * from teams where team_name like '%United%'

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

9 rows affected.

+---------+-----------------------+
| team_id |       team_name       |
+---------+-----------------------+
|    37   |    Newcastle United   |
|    39   |   Manchester United   |
|    40   |    West Ham United    |
|   101   |      Leeds United     |
|   972   |  West Ham United LFC  |
|   1214  | United States Women's |
|   1475  |   Manchester United   |
|   1839  |     United States     |
|   7285  |    NorthEast United   |
+---------+-----------------------+

In [39]:
%%sql

select matches.match_id, teams.team_name as home_team_name from matches join teams on matches.home_team_id = teams.team_id;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

3464 rows affected.

+----------+----------------+
| match_id | home_team_name |
+----------+----------------+
| 3749079  |    Arsenal     |
| 3749108  |    Arsenal     |
| 3749153  |    Arsenal     |
| 3749192  |    Arsenal     |
| 3749196  |    Arsenal     |
| 3749233  |    Arsenal     |
| 3749246  |    Arsenal     |
| 3749257  |    Arsenal     |
| 3749296  |    Arsenal     |
| 3749360  |    Arsenal     |
+----------+----------------+
Truncated to displaylimit of 10.

In [40]:
%%sql

select m.match_id, m.match_date, home.team_name as home_team_name, away.team_name as away_team_name, m.home_score, m.away_score from matches as m join teams as home on m.home_team_id = home.team_id join teams as away on m.away_team_id = away.team_id;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

3464 rows affected.

+----------+------------+------------------------+------------------------+------------+------------+
| match_id | match_date |     home_team_name     |     away_team_name     | home_score | away_score |
+----------+------------+------------------------+------------------------+------------+------------+
|   7298   | 2018-02-24 |  Manchester City WFC   |      Chelsea FCW       |     2      |     2      |
|   7430   | 2018-04-15 |   Washington Spirit    | North Carolina Courage |     2      |     4      |
|   7443   | 2018-05-05 |    Portland Thorns     |        OL Reign        |     2      |     3      |
|   7444   | 2018-05-06 | North Carolina Courage |   Chicago Red Stars    |     1      |     1      |
|   7445   | 2018-05-06 |      Utah Royals       |   Washington Spirit    |     2      |     0      |
|   7451   | 2018-05-13 | North Carolina Courage |   Washington Spirit    |     1      |     0      |
|   7456   | 2018-05-20 |    NJ/NY Gotham FC     | North Carolina Courage |     1      |     2      |
|   7457   | 2018-05-24 |     Orlando Pride      | North Carolina Courage |     3      |     4      |
|   7471   | 2018-06-30 |     Orlando Pride      | North Carolina Courage |     0      |     3      |
|   7472   | 2018-07-01 |        OL Reign        |    Portland Thorns     |     1      |     0      |
+----------+------------+------------------------+------------------------+------------+------------+
Truncated to displaylimit of 10.

In [41]:
%%sql

select count(*) from matches;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+----------+
| count(*) |
+----------+
|   3464   |
+----------+

In [42]:
%%sql

select count(*) from teams;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+----------+
| count(*) |
+----------+
|   312    |
+----------+

In [43]:
%%sql

select competition_id, count(*) as number_of_matches from matches group by competition_id;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

21 rows affected.

+----------------+-------------------+
| competition_id | number_of_matches |
+----------------+-------------------+
|       2        |        418        |
|       7        |        435        |
|       9        |        340        |
|       11       |        868        |
|       12       |        381        |
|       16       |         18        |
|       35       |         3         |
|       37       |        326        |
|       43       |        147        |
|       44       |         6         |
+----------------+-------------------+
Truncated to displaylimit of 10.

In [44]:
%%sql

select competition_id, count(*) as number_of_seasons from seasons group by competition_id;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

18 rows affected.

+----------------+-------------------+
| competition_id | number_of_seasons |
+----------------+-------------------+
|       7        |         1         |
|       9        |         2         |
|       11       |         3         |
|       12       |         1         |
|       16       |         17        |
|       35       |         1         |
|       37       |         2         |
|       43       |         8         |
|       53       |         1         |
|       55       |         1         |
+----------------+-------------------+
Truncated to displaylimit of 10.

In [45]:
%%sql

select competition_id, count(*) as number_of_matches from matches group by competition_id order by number_of_matches desc;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

21 rows affected.

+----------------+-------------------+
| competition_id | number_of_matches |
+----------------+-------------------+
|       11       |        868        |
|       7        |        435        |
|       2        |        418        |
|       12       |        381        |
|       9        |        340        |
|       37       |        326        |
|       43       |        147        |
|       72       |        116        |
|      1238      |        115        |
|       55       |        102        |
+----------------+-------------------+
Truncated to displaylimit of 10.

In [46]:
%%sql

select competition_id, count(*) as number_of_seasons from seasons group by competition_id order by number_of_seasons desc;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

18 rows affected.

+----------------+-------------------+
| competition_id | number_of_seasons |
+----------------+-------------------+
|       16       |         17        |
|       43       |         8         |
|       11       |         3         |
|       87       |         3         |
|       9        |         2         |
|       37       |         2         |
|       81       |         2         |
|      1470      |         1         |
|       7        |         1         |
|      1267      |         1         |
+----------------+-------------------+
Truncated to displaylimit of 10.

In [47]:
%%sql

select c.competition_id, c.competition_name, count(*) as number_of_seasons from seasons as s join competitions as c on s.competition_id = c.competition_id group by c.competition_id, c.competition_name order by number_of_seasons desc;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

18 rows affected.

+----------------+-------------------------+-------------------+
| competition_id |     competition_name    | number_of_seasons |
+----------------+-------------------------+-------------------+
|       16       |     Champions League    |         17        |
|       43       |      FIFA World Cup     |         8         |
|       11       |         La Liga         |         3         |
|       87       |       Copa del Rey      |         3         |
|       9        |        Bundesliga       |         2         |
|       37       | FA Women's Super League |         2         |
|       81       |     Liga Profesional    |         2         |
|      1470      |    FIFA U20 World Cup   |         1         |
|       7        |         Ligue 1         |         1         |
|      1267      |  African Cup of Nations |         1         |
+----------------+-------------------------+-------------------+
Truncated to displaylimit of 10.

In [48]:
%%sql

select c.competition_name, count(*) as number_of_matches from matches as m join competitions as c on m.competition_id = c.competition_id group by c.competition_name order by number_of_matches desc;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

21 rows affected.

+-------------------------+-------------------+
|     competition_name    | number_of_matches |
+-------------------------+-------------------+
|         La Liga         |        868        |
|         Ligue 1         |        435        |
|      Premier League     |        418        |
|         Serie A         |        381        |
|        Bundesliga       |        340        |
| FA Women's Super League |        326        |
|      FIFA World Cup     |        147        |
|    Women's World Cup    |        116        |
|   Indian Super league   |        115        |
|        UEFA Euro        |        102        |
+-------------------------+-------------------+
Truncated to displaylimit of 10.

In [49]:
%%sql

select sum(home_score) as total_home_goals from matches;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+------------------+
| total_home_goals |
+------------------+
|       5530       |
+------------------+

In [50]:
%%sql

select competition_id, sum(home_score) as total_home_goals from matches group by competition_id;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

21 rows affected.

+----------------+------------------+
| competition_id | total_home_goals |
+----------------+------------------+
|       2        |       619        |
|       7        |       642        |
|       9        |       539        |
|       11       |       1577       |
|       12       |       560        |
|       16       |        29        |
|       35       |        7         |
|       37       |       512        |
|       43       |       238        |
|       44       |        6         |
+----------------+------------------+
Truncated to displaylimit of 10.

In [51]:
%%sql

select competition_id, sum(home_score + away_score) as total_goals from matches group by competition_id;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

21 rows affected.

+----------------+-------------+
| competition_id | total_goals |
+----------------+-------------+
|       2        |     1125    |
|       7        |     1144    |
|       9        |     979     |
|       11       |     2737    |
|       12       |     983     |
|       16       |      54     |
|       35       |      8      |
|       37       |     999     |
|       43       |     406     |
|       44       |      12     |
+----------------+-------------+
Truncated to displaylimit of 10.

In [52]:
%%sql

select avg(home_score) as average_home_goals from matches;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+--------------------+
| average_home_goals |
+--------------------+
|       1.5964       |
+--------------------+

In [53]:
%%sql

select competition_id, avg(home_score) as average_home_goals from matches group by competition_id order by average_home_goals desc;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

21 rows affected.

+----------------+--------------------+
| competition_id | average_home_goals |
+----------------+--------------------+
|      1470      |       3.0000       |
|       35       |       2.3333       |
|       53       |       2.0484       |
|      116       |       2.0000       |
|       87       |       2.0000       |
|       81       |       2.0000       |
|       11       |       1.8168       |
|       43       |       1.6190       |
|       16       |       1.6111       |
|       9        |       1.5853       |
+----------------+--------------------+
Truncated to displaylimit of 10.

In [54]:
%%sql

select competition_id, count(*) as number_of_matches from matches group by competition_id having count(*) >= 100 order by number_of_matches desc;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

10 rows affected.

+----------------+-------------------+
| competition_id | number_of_matches |
+----------------+-------------------+
|       11       |        868        |
|       7        |        435        |
|       2        |        418        |
|       12       |        381        |
|       9        |        340        |
|       37       |        326        |
|       43       |        147        |
|       72       |        116        |
|      1238      |        115        |
|       55       |        102        |
+----------------+-------------------+
Truncated to displaylimit of 10.

In [55]:
%%sql

select c.competition_name, avg(m.home_score) as average_home_goals, count(*) as number_of_matches from matches as m join competitions as c on m.competition_id = c.competition_id group by c.competition_name having count(*) >= 100 order by average_home_goals desc;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

10 rows affected.

+-------------------------+--------------------+-------------------+
|     competition_name    | average_home_goals | number_of_matches |
+-------------------------+--------------------+-------------------+
|         La Liga         |       1.8168       |        868        |
|      FIFA World Cup     |       1.6190       |        147        |
|        Bundesliga       |       1.5853       |        340        |
| FA Women's Super League |       1.5706       |        326        |
|    Women's World Cup    |       1.5690       |        116        |
|   Indian Super league   |       1.5652       |        115        |
|      Premier League     |       1.4809       |        418        |
|         Ligue 1         |       1.4759       |        435        |
|         Serie A         |       1.4698       |        381        |
|        UEFA Euro        |       1.2353       |        102        |
+-------------------------+--------------------+-------------------+
Truncated to displaylimit of 10.

In [56]:
%%sql

select c.competition_name, avg(m.home_score + m.away_score) as average_total_goals, count(*) as number_of_matches from matches as m join competitions as c on m.competition_id = c.competition_id group by c.competition_name having count(*) >= 100 order by average_total_goals desc;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

10 rows affected.

+-------------------------+---------------------+-------------------+
|     competition_name    | average_total_goals | number_of_matches |
+-------------------------+---------------------+-------------------+
|         La Liga         |        3.1532       |        868        |
|   Indian Super league   |        3.0783       |        115        |
| FA Women's Super League |        3.0644       |        326        |
|        Bundesliga       |        2.8794       |        340        |
|      FIFA World Cup     |        2.7619       |        147        |
|      Premier League     |        2.6914       |        418        |
|    Women's World Cup    |        2.6724       |        116        |
|         Ligue 1         |        2.6299       |        435        |
|         Serie A         |        2.5801       |        381        |
|        UEFA Euro        |        2.5392       |        102        |
+-------------------------+---------------------+-------------------+
Truncated to displaylimit of 10.

In [59]:
%%sql

select sum(case when home_score > away_score then 1 else 0 end) as home_wins from matches;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+-----------+
| home_wins |
+-----------+
|    1565   |
+-----------+

In [60]:
%%sql

select sum(case when home_score > away_score then 1 else 0 end) as home_wins, sum(case when home_score < away_score then 1 else 0 end) as away_wins, sum(case when home_score = away_score then 1 else 0 end) as draws from matches;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+-----------+-----------+-------+
| home_wins | away_wins | draws |
+-----------+-----------+-------+
|    1565   |    1102   |  797  |
+-----------+-----------+-------+

In [61]:
%%sql

select competition_id, sum(case when home_score > away_score then 1 else 0 end) as home_wins, sum(case when home_score < away_score then 1 else 0 end) as away_wins, sum(case when home_score = away_score then 1 else 0 end) as draws from matches group by competition_id;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

21 rows affected.

+----------------+-----------+-----------+-------+
| competition_id | home_wins | away_wins | draws |
+----------------+-----------+-----------+-------+
|       2        |    172    |    127    |  119  |
|       7        |    187    |    130    |  118  |
|       9        |    149    |    114    |   77  |
|       11       |    420    |    274    |  174  |
|       12       |    175    |    111    |   95  |
|       16       |     9     |     6     |   3   |
|       35       |     3     |     0     |   0   |
|       37       |    141    |    128    |   57  |
|       43       |     70    |     48    |   29  |
|       44       |     2     |     3     |   1   |
+----------------+-----------+-----------+-------+
Truncated to displaylimit of 10.

In [63]:
%%sql

select c.competition_name, sum(case when m.home_score > m.away_score then 1 else 0 end) as home_wins, sum(case when m.home_score < m.away_score then 1 else 0 end) as away_wins, sum(case when m.home_score = m.away_score then 1 else 0 end) as draws from matches as m join competitions as c on m.competition_id = c.competition_id group by c.competition_name;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

21 rows affected.

+-------------------------+-----------+-----------+-------+
|     competition_name    | home_wins | away_wins | draws |
+-------------------------+-----------+-----------+-------+
|      Premier League     |    172    |    127    |  119  |
|         Ligue 1         |    187    |    130    |  118  |
|        Bundesliga       |    149    |    114    |   77  |
|         La Liga         |    420    |    274    |  174  |
|         Serie A         |    175    |    111    |   95  |
|     Champions League    |     9     |     6     |   3   |
|    UEFA Europa League   |     3     |     0     |   0   |
| FA Women's Super League |    141    |    128    |   57  |
|      FIFA World Cup     |     70    |     48    |   29  |
|   Major League Soccer   |     2     |     3     |   1   |
+-------------------------+-----------+-----------+-------+
Truncated to displaylimit of 10.

In [73]:
%%sql

select c.competition_name,  100.0 * sum(case when m.home_score > m.away_score then 1 else 0 end)/count(*) as home_win_percentage from matches as m join competitions as c on m.competition_id = c.competition_id group by c.competition_name having count(*) >= 100 order by home_win_percentage desc;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

10 rows affected.

+-------------------------+---------------------+
|     competition_name    | home_win_percentage |
+-------------------------+---------------------+
|    Women's World Cup    |       53.44828      |
|         La Liga         |       48.38710      |
|      FIFA World Cup     |       47.61905      |
|         Serie A         |       45.93176      |
|        Bundesliga       |       43.82353      |
| FA Women's Super League |       43.25153      |
|         Ligue 1         |       42.98851      |
|      Premier League     |       41.14833      |
|   Indian Super league   |       40.00000      |
|        UEFA Euro        |       35.29412      |
+-------------------------+---------------------+
Truncated to displaylimit of 10.

In [74]:
%%sql

select distinct competition_name from competitions;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

21 rows affected.

+-------------------------+
|     competition_name    |
+-------------------------+
|      Premier League     |
|         Ligue 1         |
|        Bundesliga       |
|         La Liga         |
|         Serie A         |
|     Champions League    |
|    UEFA Europa League   |
| FA Women's Super League |
|      FIFA World Cup     |
|   Major League Soccer   |
+-------------------------+
Truncated to displaylimit of 10.

In [30]:
lineups_file = Path("../data/raw_data/lineups")

players_list = []
lineups_list = []
countries_list = []

for item in lineups_file.iterdir():    
    with open(item, 'r') as f:
        data = json.load(f)

    for team in data:
        for player in team['lineup']:
            player_dict = {
            'player_id': player['player_id'],
            'player_name': player['player_name'],
            'country_id': player.get('country', {}).get('id')
            }
            lineup_dict = {
            'match_id': int(item.stem),
            'team_id': team['team_id'],
            'player_id': player['player_id'],
            'jersey_number': player['jersey_number']
            }
            countries_dict = {
            'country_id': player.get('country', {}).get('id'),
            'country_name': player.get('country', {}).get('name')
            }
            players_list.append(player_dict)
            lineups_list.append(lineup_dict)
            countries_list.append(countries_dict)
print(players_list[0])
print(lineups_list[0])
print(countries_list[0])

{'player_id': 3287, 'player_name': 'Nathaniel Chalobah', 'country_id': 68}
{'match_id': 3879769, 'team_id': 227, 'player_id': 3287, 'jersey_number': 94}
{'country_id': 68, 'country_name': 'England'}

In [31]:
players_df = pd.DataFrame(players_list)
lineups_df = pd.DataFrame(lineups_list)
countries_df = pd.DataFrame(countries_list)

print(len(players_df))
print(len(lineups_df))
print(len(countries_df))

players_df = players_df.drop_duplicates(subset=['player_id']).reset_index(drop=True)
countries_df = countries_df.drop_duplicates(subset=['country_id']).reset_index(drop=True)

print(len(players_df))
print(len(countries_df))

131901
131901
131901
10803
142

In [32]:
countries_df[countries_df.isna().any(axis=1)]

    country_id country_name
61         NaN         None

In [33]:
countries_df = countries_df.dropna()

In [36]:
countries_df.isna().sum()

country_id      0
country_name    0
dtype: int64

In [37]:
countries_df.to_sql(name='countries', con=engine, if_exists="append", index=False)

141

In [38]:
players_df.to_sql(name='players', con=engine, if_exists="append", index=False)

10803

In [39]:
lineups_df.to_sql(name='lineups', con=engine, if_exists="append", index=False)

131901

In [6]:
%%sql

create table if not exists events(
    event_id char(36) primary key,
    match_id int not null,
    event_index int not null,
    period int not null,
    timestamp varchar(20) not null,
    minute int not null,
    second int not null,
    possession int not null,
    possession_team_id int not null,
    team_id int not null,
    position_id int,
    duration double,
    under_pressure boolean,
    event_type varchar(100) not null,
    player_id int,
    location_x double,
    location_y double, 

    foreign key (match_id) references matches(match_id),
    foreign key (possession_team_id) references teams(team_id),
    foreign key (team_id) references teams(team_id),
    foreign key (player_id) references players(player_id)
);

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

++
||
++
++

In [7]:
events_dir = Path("../data/processed_data")
events_batch = pd.read_parquet(events_dir/"events_0000.parquet")

print(events_batch.shape)
print(events_batch.head())
print(events_batch.dtypes)

(353140, 17)
   match_id                              event_id  event_index  period  \
0     15946  9f6e2ecf-6685-45df-a62e-c2db3090f6c1            1       1
1     15946  0300039d-150d-41e4-b29a-76602ef002e6            2       1
2     15946  491e8901-7630-4cc8-b57b-937dddff2eaa            3       1
3     15946  757b85ad-ddfe-44d5-b893-c23a9fb709d8            4       1
4     15946  549567bd-36de-4ac8-b8dc-6b5d3f1e4be8            5       1

      timestamp  minute  second  possession  possession_team_id  team_id  \
0  00:00:00.000       0       0           1                 217      217
1  00:00:00.000       0       0           1                 217      206
2  00:00:00.000       0       0           1                 217      217
3  00:00:00.000       0       0           1                 217      206
4  00:00:00.575       0       0           2                 206      206

   position_id  duration under_pressure   event_type  player_id  location_x  \
0          NaN  0.000000           None  Starting XI        NaN         NaN
1          NaN  0.000000           None  Starting XI        NaN         NaN
2          NaN  0.000000           None   Half Start        NaN         NaN
3          NaN  0.000000           None   Half Start        NaN         NaN
4         16.0  2.015669           None         Pass     6581.0        61.0

   location_y
0         NaN
1         NaN
2         NaN
3         NaN
4        40.1
match_id                int64
event_id               object
event_index             int64
period                  int64
timestamp              object
minute                  int64
second                  int64
possession              int64
possession_team_id      int64
team_id                 int64
position_id           float64
duration              float64
under_pressure         object
event_type             object
player_id             float64
location_x            float64
location_y            float64
dtype: object

In [40]:
events_batch.to_sql(name="events", con=engine, if_exists="append", index=False, chunksize=5000)

353140

In [41]:
%%sql

select count(*) from events;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+----------+
| count(*) |
+----------+
|  353140  |
+----------+

In [9]:
event_files = sorted(events_dir.glob("events_*.parquet"))
file_statuses = []

with engine.connect() as connection:
    for event_file in event_files:
        batch_ids = pd.read_parquet(
            event_file,
            columns=["match_id"],
        )

        expected_rows = len(batch_ids)
        match_ids = batch_ids["match_id"].drop_duplicates().tolist()

        placeholders = ", ".join(
            f":match_id_{i}" for i in range(len(match_ids))
        )

        parameters = {
            f"match_id_{i}": match_id
            for i, match_id in enumerate(match_ids)
        }

        query = text(
            f"""
            SELECT COUNT(*)
            FROM events
            WHERE match_id IN ({placeholders})
            """
        )

        loaded_rows = connection.execute(
            query,
            parameters,
        ).scalar_one()

        if loaded_rows == 0:
            status = "not loaded"
        elif loaded_rows == expected_rows:
            status = "fully loaded"
        else:
            status = "partially loaded"

        file_statuses.append(
            {
                "file": event_file.name,
                "expected_rows": expected_rows,
                "loaded_rows": loaded_rows,
                "status": status,
            }
        )

        print(
            f"{event_file.name}: "
            f"{loaded_rows}/{expected_rows} — {status}"
        )

events_0000.parquet: 353140/353140 — fully loaded
events_0001.parquet: 337832/337832 — fully loaded
events_0002.parquet: 349748/349748 — fully loaded
events_0003.parquet: 375970/375970 — fully loaded
events_0004.parquet: 354870/354870 — fully loaded
events_0005.parquet: 344059/344059 — fully loaded
events_0006.parquet: 344475/344475 — fully loaded
events_0007.parquet: 345726/345726 — fully loaded
events_0008.parquet: 361633/361633 — fully loaded
events_0009.parquet: 340863/340863 — fully loaded
events_0010.parquet: 371525/371525 — fully loaded
events_0011.parquet: 298998/298998 — fully loaded
events_0012.parquet: 335874/335874 — fully loaded
events_0013.parquet: 334838/334838 — fully loaded
events_0014.parquet: 341098/341098 — fully loaded
events_0015.parquet: 341607/341607 — fully loaded
events_0016.parquet: 352717/352717 — fully loaded
events_0017.parquet: 377637/377637 — fully loaded
events_0018.parquet: 353050/353050 — fully loaded
events_0019.parquet: 358574/358574 — fully loaded
events_0020.parquet: 0/357060 — not loaded
events_0021.parquet: 0/353068 — not loaded
events_0022.parquet: 0/340091 — not loaded
events_0023.parquet: 0/353189 — not loaded
events_0024.parquet: 0/352623 — not loaded
events_0025.parquet: 0/365872 — not loaded
events_0026.parquet: 0/362224 — not loaded
events_0027.parquet: 0/362463 — not loaded
events_0028.parquet: 0/355989 — not loaded
events_0029.parquet: 0/334627 — not loaded
events_0030.parquet: 0/346492 — not loaded
events_0031.parquet: 0/354544 — not loaded
events_0032.parquet: 0/386658 — not loaded
events_0033.parquet: 0/351393 — not loaded
events_0034.parquet: 0/238422 — not loaded

In [11]:
event_files = sorted(events_dir.glob('events_*.parquet'))

for event_file in event_files[20:]:
    events_batch = pd.read_parquet(event_file)
    inserted_rows = events_batch.to_sql(name="events", con=engine, if_exists="append", index=False, chunksize=5000)

    print(f"{event_file.name}: {len(events_batch)} rows loaded")

events_0020.parquet: 357060 rows loaded
events_0021.parquet: 353068 rows loaded
events_0022.parquet: 340091 rows loaded
events_0023.parquet: 353189 rows loaded
events_0024.parquet: 352623 rows loaded
events_0025.parquet: 365872 rows loaded
events_0026.parquet: 362224 rows loaded
events_0027.parquet: 362463 rows loaded
events_0028.parquet: 355989 rows loaded
events_0029.parquet: 334627 rows loaded
events_0030.parquet: 346492 rows loaded
events_0031.parquet: 354544 rows loaded
events_0032.parquet: 386658 rows loaded
events_0033.parquet: 351393 rows loaded
events_0034.parquet: 238422 rows loaded

In [12]:
%%sql
    
select count(*) from events;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+----------+
| count(*) |
+----------+
| 12188949 |
+----------+

In [13]:
expected_event_rows = sum(len(pd.read_parquet(event_file, columns=["event_id"])) for event_file in event_files)
print(expected_event_rows)

12188949

In [16]:
passes_files = sorted(events_dir.glob('passes_*.parquet'))

for pass_file in passes_files:
    passes_batch = pd.read_parquet(pass_file)
    inserted_rows = passes_batch.to_sql(name="passes", con=engine, if_exists="append", index=False, chunksize=5000)
    print(f"{pass_file.name}: {len(passes_batch)} rows loaded")

passes_0000.parquet: 99516 rows loaded
passes_0001.parquet: 90438 rows loaded
passes_0002.parquet: 95131 rows loaded
passes_0003.parquet: 104603 rows loaded
passes_0004.parquet: 99934 rows loaded
passes_0005.parquet: 96639 rows loaded
passes_0006.parquet: 97010 rows loaded
passes_0007.parquet: 97120 rows loaded
passes_0008.parquet: 102119 rows loaded
passes_0009.parquet: 93505 rows loaded
passes_0010.parquet: 104847 rows loaded
passes_0011.parquet: 83006 rows loaded
passes_0012.parquet: 94718 rows loaded
passes_0013.parquet: 94295 rows loaded
passes_0014.parquet: 96209 rows loaded
passes_0015.parquet: 96038 rows loaded
passes_0016.parquet: 97070 rows loaded
passes_0017.parquet: 108975 rows loaded
passes_0018.parquet: 97150 rows loaded
passes_0019.parquet: 98863 rows loaded
passes_0020.parquet: 98281 rows loaded
passes_0021.parquet: 97674 rows loaded
passes_0022.parquet: 93653 rows loaded
passes_0023.parquet: 97318 rows loaded
passes_0024.parquet: 97352 rows loaded
passes_0025.parquet: 100124 rows loaded
passes_0026.parquet: 99373 rows loaded
passes_0027.parquet: 99940 rows loaded
passes_0028.parquet: 98078 rows loaded
passes_0029.parquet: 93614 rows loaded
passes_0030.parquet: 95462 rows loaded
passes_0031.parquet: 96862 rows loaded
passes_0032.parquet: 107653 rows loaded
passes_0033.parquet: 97952 rows loaded
passes_0034.parquet: 67238 rows loaded

In [17]:
%%sql

select count(*) from passes;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+----------+
| count(*) |
+----------+
| 3387760  |
+----------+

In [18]:
expected_pass_rows = sum(len(pd.read_parquet(event_file, columns=["event_id"])) for event_file in passes_files)
print(expected_pass_rows)

3387760

In [19]:
carries_files = sorted(events_dir.glob('carries_*.parquet'))

for carry_file in carries_files:
    carry_batch = pd.read_parquet(carry_file)
    inserted_rows = carry_batch.to_sql(name="carries", con=engine, if_exists="append", index=False, chunksize=5000)
    print(f"{carry_file.name}: {len(carry_batch)} rows loaded")

carries_0000.parquet: 82199 rows loaded
carries_0001.parquet: 73114 rows loaded
carries_0002.parquet: 78133 rows loaded
carries_0003.parquet: 87249 rows loaded
carries_0004.parquet: 77474 rows loaded
carries_0005.parquet: 72573 rows loaded
carries_0006.parquet: 72535 rows loaded
carries_0007.parquet: 72673 rows loaded
carries_0008.parquet: 79992 rows loaded
carries_0009.parquet: 72834 rows loaded
carries_0010.parquet: 84408 rows loaded
carries_0011.parquet: 61191 rows loaded
carries_0012.parquet: 71006 rows loaded
carries_0013.parquet: 70111 rows loaded
carries_0014.parquet: 72042 rows loaded
carries_0015.parquet: 72662 rows loaded
carries_0016.parquet: 74688 rows loaded
carries_0017.parquet: 87514 rows loaded
carries_0018.parquet: 74222 rows loaded
carries_0019.parquet: 73709 rows loaded
carries_0020.parquet: 73621 rows loaded
carries_0021.parquet: 74121 rows loaded
carries_0022.parquet: 69081 rows loaded
carries_0023.parquet: 71766 rows loaded
carries_0024.parquet: 71629 rows loaded
carries_0025.parquet: 79609 rows loaded
carries_0026.parquet: 75562 rows loaded
carries_0027.parquet: 75029 rows loaded
carries_0028.parquet: 74710 rows loaded
carries_0029.parquet: 74739 rows loaded
carries_0030.parquet: 77578 rows loaded
carries_0031.parquet: 81140 rows loaded
carries_0032.parquet: 90529 rows loaded
carries_0033.parquet: 79025 rows loaded
carries_0034.parquet: 54102 rows loaded

In [20]:
%%sql

select count(*) from carries;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+----------+
| count(*) |
+----------+
| 2632570  |
+----------+

In [21]:
expected_carry_rows = sum(len(pd.read_parquet(event_file, columns=["event_id"])) for event_file in carries_files)
print(expected_carry_rows)

2632570

In [22]:
duels_files = sorted(events_dir.glob('duels_*.parquet'))

for duel_file in duels_files:
    duels_batch = pd.read_parquet(duel_file)
    inserted_rows = duels_batch.to_sql(name="duels", con=engine, if_exists="append", index=False, chunksize=5000)
    print(f"{duel_file.name}: {len(duels_batch)} rows loaded")

duels_0000.parquet: 5832 rows loaded
duels_0001.parquet: 6845 rows loaded
duels_0002.parquet: 6734 rows loaded
duels_0003.parquet: 6138 rows loaded
duels_0004.parquet: 7539 rows loaded
duels_0005.parquet: 8401 rows loaded
duels_0006.parquet: 8568 rows loaded
duels_0007.parquet: 8617 rows loaded
duels_0008.parquet: 7227 rows loaded
duels_0009.parquet: 6730 rows loaded
duels_0010.parquet: 6300 rows loaded
duels_0011.parquet: 6871 rows loaded
duels_0012.parquet: 8201 rows loaded
duels_0013.parquet: 8479 rows loaded
duels_0014.parquet: 8848 rows loaded
duels_0015.parquet: 8314 rows loaded
duels_0016.parquet: 8059 rows loaded
duels_0017.parquet: 6535 rows loaded
duels_0018.parquet: 7315 rows loaded
duels_0019.parquet: 7913 rows loaded
duels_0020.parquet: 7591 rows loaded
duels_0021.parquet: 7324 rows loaded
duels_0022.parquet: 8220 rows loaded
duels_0023.parquet: 8386 rows loaded
duels_0024.parquet: 8702 rows loaded
duels_0025.parquet: 7203 rows loaded
duels_0026.parquet: 8592 rows loaded
duels_0027.parquet: 8740 rows loaded
duels_0028.parquet: 8082 rows loaded
duels_0029.parquet: 6286 rows loaded
duels_0030.parquet: 6849 rows loaded
duels_0031.parquet: 6813 rows loaded
duels_0032.parquet: 6815 rows loaded
duels_0033.parquet: 5389 rows loaded
duels_0034.parquet: 3403 rows loaded

In [23]:
%%sql

select count(*) from duels;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+----------+
| count(*) |
+----------+
|  257861  |
+----------+

In [24]:
expected_duel_rows = sum(len(pd.read_parquet(event_file, columns=["event_id"])) for event_file in duels_files)
print(expected_duel_rows)

257861

In [25]:
shots_files = sorted(events_dir.glob('shots_*.parquet'))

for shot_file in shots_files:
    shots_batch = pd.read_parquet(shot_file)
    inserted_rows = shots_batch.to_sql(name="shots", con=engine, if_exists="append", index=False, chunksize=5000)
    print(f"{shot_file.name}: {len(shots_batch)} rows loaded")

shots_0000.parquet: 2785 rows loaded
shots_0001.parquet: 2523 rows loaded
shots_0002.parquet: 2556 rows loaded
shots_0003.parquet: 2509 rows loaded
shots_0004.parquet: 2477 rows loaded
shots_0005.parquet: 2589 rows loaded
shots_0006.parquet: 2580 rows loaded
shots_0007.parquet: 2638 rows loaded
shots_0008.parquet: 2567 rows loaded
shots_0009.parquet: 2450 rows loaded
shots_0010.parquet: 2540 rows loaded
shots_0011.parquet: 2668 rows loaded
shots_0012.parquet: 2589 rows loaded
shots_0013.parquet: 2335 rows loaded
shots_0014.parquet: 2382 rows loaded
shots_0015.parquet: 2309 rows loaded
shots_0016.parquet: 2559 rows loaded
shots_0017.parquet: 2482 rows loaded
shots_0018.parquet: 2647 rows loaded
shots_0019.parquet: 2623 rows loaded
shots_0020.parquet: 2572 rows loaded
shots_0021.parquet: 2831 rows loaded
shots_0022.parquet: 2657 rows loaded
shots_0023.parquet: 2582 rows loaded
shots_0024.parquet: 2521 rows loaded
shots_0025.parquet: 2604 rows loaded
shots_0026.parquet: 2297 rows loaded
shots_0027.parquet: 2334 rows loaded
shots_0028.parquet: 2378 rows loaded
shots_0029.parquet: 2478 rows loaded
shots_0030.parquet: 2720 rows loaded
shots_0031.parquet: 2558 rows loaded
shots_0032.parquet: 2280 rows loaded
shots_0033.parquet: 2631 rows loaded
shots_0034.parquet: 1772 rows loaded

In [26]:
%%sql

select count(*) from shots;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+----------+
| count(*) |
+----------+
|  88023   |
+----------+

In [27]:
expected_shots_rows = sum(len(pd.read_parquet(event_file, columns=["event_id"])) for event_file in shots_files)
print(expected_shots_rows)

88023

In [28]:
dribbles_files = sorted(events_dir.glob('dribbles_*.parquet'))

for dribble_file in dribbles_files:
    dribbles_batch = pd.read_parquet(dribble_file)
    inserted_rows = dribbles_batch.to_sql(name="dribbles", con=engine, if_exists="append", index=False, chunksize=5000)
    print(f"{dribble_file.name}: {len(dribbles_batch)} rows loaded")

dribbles_0000.parquet: 3603 rows loaded
dribbles_0001.parquet: 3644 rows loaded
dribbles_0002.parquet: 4130 rows loaded
dribbles_0003.parquet: 4697 rows loaded
dribbles_0004.parquet: 3898 rows loaded
dribbles_0005.parquet: 3536 rows loaded
dribbles_0006.parquet: 3648 rows loaded
dribbles_0007.parquet: 3633 rows loaded
dribbles_0008.parquet: 3597 rows loaded
dribbles_0009.parquet: 3548 rows loaded
dribbles_0010.parquet: 3384 rows loaded
dribbles_0011.parquet: 3015 rows loaded
dribbles_0012.parquet: 3655 rows loaded
dribbles_0013.parquet: 3735 rows loaded
dribbles_0014.parquet: 3876 rows loaded
dribbles_0015.parquet: 3432 rows loaded
dribbles_0016.parquet: 3305 rows loaded
dribbles_0017.parquet: 3065 rows loaded
dribbles_0018.parquet: 3153 rows loaded
dribbles_0019.parquet: 3074 rows loaded
dribbles_0020.parquet: 3178 rows loaded
dribbles_0021.parquet: 3277 rows loaded
dribbles_0022.parquet: 3100 rows loaded
dribbles_0023.parquet: 3069 rows loaded
dribbles_0024.parquet: 3002 rows loaded
dribbles_0025.parquet: 3067 rows loaded
dribbles_0026.parquet: 3272 rows loaded
dribbles_0027.parquet: 3347 rows loaded
dribbles_0028.parquet: 3218 rows loaded
dribbles_0029.parquet: 2617 rows loaded
dribbles_0030.parquet: 3903 rows loaded
dribbles_0031.parquet: 4560 rows loaded
dribbles_0032.parquet: 4834 rows loaded
dribbles_0033.parquet: 3603 rows loaded
dribbles_0034.parquet: 2372 rows loaded

In [29]:
%%sql

select count(*) from dribbles;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+----------+
| count(*) |
+----------+
|  122047  |
+----------+

In [30]:
expected_dribbles_rows = sum(len(pd.read_parquet(event_file, columns=["event_id"])) for event_file in dribbles_files)
print(expected_dribbles_rows)

122047

In [31]:
%%sql
    
select count(*) as total_events from events;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+--------------+
| total_events |
+--------------+
|   12188949   |
+--------------+

In [32]:
%%sql

select count(player_id) as events_with_players from events;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+---------------------+
| events_with_players |
+---------------------+
|       12136895      |
+---------------------+

In [33]:
%%sql

select count(distinct player_id) as unique_players from events;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+----------------+
| unique_players |
+----------------+
|      9043      |
+----------------+

In [35]:
%%sql

select distinct event_type from events order by event_type;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

35 rows affected.

+---------------+
|   event_type  |
+---------------+
|     50/50     |
| Bad Behaviour |
| Ball Receipt* |
| Ball Recovery |
|     Block     |
|   Camera off  |
|   Camera On   |
|     Carry     |
|   Clearance   |
|  Dispossessed |
+---------------+
Truncated to displaylimit of 10.

In [36]:
%%sql

select count(distinct event_type) as number_of_event_types from events;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+-----------------------+
| number_of_event_types |
+-----------------------+
|           35          |
+-----------------------+

In [38]:
%%sql

select event_type, count(distinct player_id) as unique_players from events group by event_type order by unique_players desc;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

35 rows affected.

+----------------+----------------+
|   event_type   | unique_players |
+----------------+----------------+
| Ball Receipt*  |      9006      |
|      Pass      |      8995      |
|     Carry      |      8986      |
|    Pressure    |      8584      |
| Ball Recovery  |      8501      |
|      Duel      |      7801      |
|     Block      |      7346      |
| Foul Committed |      7208      |
| Dribbled Past  |      6931      |
|    Foul Won    |      6887      |
+----------------+----------------+
Truncated to displaylimit of 10.

In [40]:
%%sql

describe passes;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

6 rows affected.

+----------------+--------+------+-----+---------+-------+
|     Field      |  Type  | Null | Key | Default | Extra |
+----------------+--------+------+-----+---------+-------+
|    event_id    |  text  | YES  |     |   None  |       |
|  recipient_id  | double | YES  |     |   None  |       |
|     length     | double | YES  |     |   None  |       |
|   outcome_id   | double | YES  |     |   None  |       |
| end_location_x | double | YES  |     |   None  |       |
| end_location_y | double | YES  |     |   None  |       |
+----------------+--------+------+-----+---------+-------+

In [41]:
%%sql

describe events;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

17 rows affected.

+--------------------+-------------+------+-----+---------+-------+
|       Field        |     Type    | Null | Key | Default | Extra |
+--------------------+-------------+------+-----+---------+-------+
|      event_id      |   char(36)  |  NO  | PRI |   None  |       |
|      match_id      |     int     |  NO  | MUL |   None  |       |
|    event_index     |     int     |  NO  |     |   None  |       |
|       period       |     int     |  NO  |     |   None  |       |
|     timestamp      | varchar(20) |  NO  |     |   None  |       |
|       minute       |     int     |  NO  |     |   None  |       |
|       second       |     int     |  NO  |     |   None  |       |
|     possession     |     int     |  NO  |     |   None  |       |
| possession_team_id |     int     |  NO  | MUL |   None  |       |
|      team_id       |     int     |  NO  | MUL |   None  |       |
+--------------------+-------------+------+-----+---------+-------+
Truncated to displaylimit of 10.

In [42]:
%%sql

select * from events limit 5;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

5 rows affected.

+--------------------------------------+----------+-------------+--------+--------------+--------+--------+------------+--------------------+---------+-------------+----------+----------------+---------------+-----------+------------+------------+
|               event_id               | match_id | event_index | period |  timestamp   | minute | second | possession | possession_team_id | team_id | position_id | duration | under_pressure |   event_type  | player_id | location_x | location_y |
+--------------------------------------+----------+-------------+--------+--------------+--------+--------+------------+--------------------+---------+-------------+----------+----------------+---------------+-----------+------------+------------+
| 000000b5-8156-429d-9088-e62a6ac2ea0d | 3754015  |     2529    |   2    | 00:15:18.727 |   60   |   18   |    123     |         39         |    39   |      5      | 1.013174 |      None      |     Carry     |   10958   |    36.8    |    20.0    |
| 00000568-d82a-47f5-8219-78debe3449b3 | 3825817  |     1659    |   2    | 00:01:21.794 |   46   |   21   |    110     |        216         |   216   |      2      | 1.358244 |      None      |      Pass     |    6627   |    74.1    |    53.3    |
| 000005b2-d8ff-4c0c-aa5c-2c91130fdc3b | 3857256  |     948     |   1    | 00:27:32.915 |   27   |   32   |     70     |        786         |   786   |      3      | 2.781358 |      None      |     Carry     |    5603   |    35.4    |    58.6    |
| 000008b5-1c29-471f-a612-3a939ff8f29a | 3890360  |     1529    |   2    | 00:01:01.039 |   46   |   1    |     88     |        872         |   171   |      5      |   0.0    |      None      | Dribbled Past |   26791   |    8.1     |    62.0    |
| 00000b67-c85c-4825-a0cd-0d167ca51aa8 | 3890285  |     2037    |   2    | 00:12:27.939 |   57   |   27   |    120     |        176         |   176   |      19     | 1.601128 |      None      |      Pass     |    8762   |    99.7    |    4.7     |
+--------------------------------------+----------+-------------+--------+--------------+--------+--------+------------+--------------------+---------+-------------+----------+----------------+---------------+-----------+------------+------------+

In [43]:
%%sql

select * from passes limit 5;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

5 rows affected.

+--------------------------------------+--------------+------------+------------+----------------+----------------+
|               event_id               | recipient_id |   length   | outcome_id | end_location_x | end_location_y |
+--------------------------------------+--------------+------------+------------+----------------+----------------+
| 549567bd-36de-4ac8-b8dc-6b5d3f1e4be8 |    6855.0    |  29.76995  |    None    |      33.8      |      28.0      |
| 4e4e4cad-9897-43ec-842d-585a4077f6ce |    6613.0    | 68.335205  |    9.0     |      86.5      |      74.2      |
| be27cc25-92b5-4696-b43c-aad957a6119a |    5470.0    | 12.4903965 |    None    |      35.1      |      18.3      |
| b33c0b7f-7456-4efe-b43c-5fd7cbd14689 |    5477.0    | 13.046455  |    None    |      36.2      |      5.3       |
| c587e5ce-fe6e-4cfb-b510-8a8e193699d3 |    5211.0    |  9.585927  |    None    |      25.3      |      1.6       |
+--------------------------------------+--------------+------------+------------+----------------+----------------+

In [45]:
%%sql

select count(case when event_type = 'Pass' then 1 end) as pass_count from events;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

1 rows affected.

+------------+
| pass_count |
+------------+
|  3387760   |
+------------+

In [46]:
%%sql

select player_id, count(case when event_type = 'Pass' then 1 end) as number_of_passes from events group by player_id order by number_of_passes desc;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

9044 rows affected.

+-----------+------------------+
| player_id | number_of_passes |
+-----------+------------------+
|    5503   |      33088       |
|    5203   |      28754       |
|   20131   |      23388       |
|    5213   |      21644       |
|    5216   |      20467       |
|    5211   |      20174       |
|    4324   |      18496       |
|    5470   |      12419       |
|    5506   |      12321       |
|    6379   |       9737       |
+-----------+------------------+
Truncated to displaylimit of 10.

In [51]:
%%sql

describe players;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

3 rows affected.

+-------------+--------------+------+-----+---------+-------+
|    Field    |     Type     | Null | Key | Default | Extra |
+-------------+--------------+------+-----+---------+-------+
|  player_id  |     int      |  NO  | PRI |   None  |       |
| player_name | varchar(255) |  NO  |     |   None  |       |
|  country_id |     int      | YES  | MUL |   None  |       |
+-------------+--------------+------+-----+---------+-------+

In [52]:
%%sql

select p.player_name, count(case when e.event_type = 'Pass' then 1 end) as number_of_passes from events as e join players as p on e.player_id = p.player_id group by p.player_name order by number_of_passes desc;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

9038 rows affected.

+--------------------------------+------------------+
|          player_name           | number_of_passes |
+--------------------------------+------------------+
| Lionel Andrés Messi Cuccittini |      33088       |
|    Sergio Busquets i Burgos    |      28754       |
|     Xavier Hernández Creus     |      23388       |
|     Gerard Piqué Bernabéu      |      21644       |
|      Andrés Iniesta Luján      |      20467       |
|        Jordi Alba Ramos        |      20174       |
|     Daniel Alves da Silva      |      18496       |
|          Ivan Rakitić          |      12419       |
|  Javier Alejandro Mascherano   |      12321       |
|     Sergi Roberto Carnicer     |       9737       |
+--------------------------------+------------------+
Truncated to displaylimit of 10.

In [53]:
%%sql

select player_id, count(*) as number_of_passes from events where event_type = 'Pass' group by player_id order by number_of_passes desc;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

8995 rows affected.

+-----------+------------------+
| player_id | number_of_passes |
+-----------+------------------+
|    5503   |      33088       |
|    5203   |      28754       |
|   20131   |      23388       |
|    5213   |      21644       |
|    5216   |      20467       |
|    5211   |      20174       |
|    4324   |      18496       |
|    5470   |      12419       |
|    5506   |      12321       |
|    6379   |       9737       |
+-----------+------------------+
Truncated to displaylimit of 10.

In [54]:
%%sql
    
select player_id, sum(case when event_type = 'Pass' then 1 else 0 end) as passes, sum(case when event_type = 'Shot' then 1 else 0 end) as shots, sum(case when event_type = 'carry' then 1 else 0 end) as carries from events group by player_id;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

9044 rows affected.

+-----------+--------+-------+---------+
| player_id | passes | shots | carries |
+-----------+--------+-------+---------+
|    None   |   0    |   0   |    0    |
|    2935   |  503   |   7   |   383   |
|    2936   |  1107  |   4   |   706   |
|    2937   |   44   |   0   |    42   |
|    2940   |   9    |   0   |    9    |
|    2941   |  213   |   20  |   271   |
|    2943   |  621   |   4   |   453   |
|    2944   |  264   |   11  |   192   |
|    2946   |  1322  |   13  |   871   |
|    2947   |  1148  |   0   |   527   |
+-----------+--------+-------+---------+
Truncated to displaylimit of 10.