In [1]:
import pandas as pd
import numpy as np
import json
import copy
import matplotlib.pyplot as plt

from pathlib import Path
from getpass import getpass
from sqlalchemy import URL, create_engine, text

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import torch
import torch.optim as optim
import torch.nn as nn
import random

from torch.utils.data import TensorDataset, DataLoader

In [2]:
password = getpass("Enter your MYSQL password: ")

connection_url = URL.create(drivername="mysql+pymysql", username="notebook_user", password=password, host="localhost", port=3306, database="football_db")

engine = create_engine(connection_url)

Enter your MYSQL password:  ········

In [3]:
%load_ext sql
%sql engine

In [4]:
lineup_dir = Path("../data/raw_data/lineups")
item = next(lineup_dir.iterdir())

match_id = int(item.stem)
match_id

3879769

In [5]:
event_file = Path("../data/raw_data/events") / f"{match_id}.json"

with open(event_file, "r") as f:
    event_data = json.load(f)

half_end_events = [event for event in event_data if event["type"]["name"] == "Half End" and event["period"] <= 4]

last_half_end = max(half_end_events, key=lambda event: (event["period"], event["minute"], event["second"]))

match_end_time = f"{last_half_end['minute']}:{last_half_end['second']:02d}"

print(match_id, match_end_time)

3879769 93:00

In [6]:
def time_to_seconds(time_string):
    minute, seconds = time_string.split(":")
    return int(minute) * 60 + int(seconds)

In [7]:
def calculate_player_minutes(positions, match_end_time):
    match_end = time_to_seconds(match_end_time)
    intervals = []

    for position in positions:
        start = max(0, time_to_seconds(position["from"]))
        end = match_end if position["to"] is None else min(time_to_seconds(position["to"]), match_end)
        if end > start:
            intervals.append((start, end))

    if not intervals:
        return 0

    intervals.sort()
    merged = [intervals[0]]

    for start, end in intervals[1:]:
        last_start, last_end = merged[-1]
        if start <= last_end:
            merged[-1] = (last_start, max(last_end, end))
        else:
            merged.append((start, end))

    return sum(end - start for start, end in merged) / 60

In [8]:
lineup_file = Path("../data/raw_data/lineups") / f"{match_id}.json"

with open(lineup_file, "r") as f:
    lineup_data = json.load(f)

player_minutes = []

for team in lineup_data:
    team_id = team["team_id"]

    for player in team["lineup"]:
        if len(player["positions"]) == 0:
            continue

        minutes_played = calculate_player_minutes(player["positions"], match_end_time)

        player_minutes.append({
            "player_id": player["player_id"],
            "team_id": team_id,
            "match_id": match_id,
            "minutes_played": minutes_played
        })

player_minutes_df = pd.DataFrame(player_minutes)
player_minutes_df.head()

   player_id  team_id  match_id  minutes_played
0       3287      227   3879769        7.366667
1       5497      227   3879769       93.000000
2       5630      227   3879769       22.266667
3       5675      227   3879769       93.000000
4       6754      227   3879769       66.750000

In [9]:
print(player_minutes_df.shape)
print(player_minutes_df["minutes_played"].describe())

(28, 4)
count    28.000000
mean     73.071429
std      28.186253
min       7.366667
25%      61.475000
50%      93.000000
75%      93.000000
max      93.000000
Name: minutes_played, dtype: float64

In [10]:
player_minutes = []

for item in lineup_dir.iterdir():
    with open(item, 'r') as f:
        lineup_data = json.load(f)

    match_id = int(item.stem)
    event_file = Path("../data/raw_data/events") / f"{match_id}.json"

    with open(event_file, 'r') as f:
        event_data = json.load(f)
        
    half_end_events = [event for event in event_data if event["type"]["name"] == "Half End" and event["period"] <= 4]
    last_half_end = max(half_end_events, key=lambda event: (event["period"], event["minute"], event["second"]))
    match_end_time = f"{last_half_end['minute']}:{last_half_end['second']:02d}"
    
    for team in lineup_data:
        team_id = team['team_id']
        for player in team['lineup']:
            if len(player["positions"]) == 0:
                continue

            minutes_played = calculate_player_minutes(player["positions"], match_end_time)
            player_minutes.append({
            "player_id": player["player_id"],
            "team_id": team_id,
            "match_id": match_id,
            "minutes_played": minutes_played
        })

player_minutes_df = pd.DataFrame(player_minutes)
player_minutes_df.head()

   player_id  team_id  match_id  minutes_played
0       3287      227   3879769        7.366667
1       5497      227   3879769       93.000000
2       5630      227   3879769       22.266667
3       5675      227   3879769       93.000000
4       6754      227   3879769       66.750000

In [11]:
print(player_minutes_df.shape)
print(player_minutes_df["minutes_played"].describe())
print(player_minutes_df.duplicated(subset=["player_id", "team_id", "match_id"]).sum())
print((player_minutes_df["minutes_played"] <= 0).sum())

(97722, 4)
count    97722.000000
mean        73.652101
std         29.458124
min          0.000000
25%         56.783333
50%         92.100000
75%         94.050000
max        127.633333
Name: minutes_played, dtype: float64
0
1

In [12]:
problem_minutes = player_minutes_df[(player_minutes_df["minutes_played"] <= 0) | (player_minutes_df["minutes_played"] > 130)].copy()
problem_minutes

       player_id  team_id  match_id  minutes_played
63680      49913      863   3893806             0.0

In [13]:
print(problem_minutes.sort_values("minutes_played"))

       player_id  team_id  match_id  minutes_played
63680      49913      863   3893806             0.0

In [14]:
problem_match_id = 3893806
problem_player_id = 49913

lineup_file = Path("../data/raw_data/lineups") / f"{problem_match_id}.json"

with open(lineup_file, "r") as f:
    lineup_data = json.load(f)

for team in lineup_data:
    for player in team["lineup"]:
        if player["player_id"] == problem_player_id:
            print(player["player_name"])
            print(player["positions"])

Athenea del Castillo Belvide
[{'position_id': 21, 'position': 'Left Wing', 'from': '100:16', 'to': '96:36', 'from_period': 2, 'to_period': 2, 'start_reason': 'Player On', 'end_reason': 'Player Off'}]

In [15]:
player_minutes_df = player_minutes_df[player_minutes_df["minutes_played"] > 0].copy()

In [16]:
query_path = Path("../database/player_features.sql")
query = query_path.read_text()

In [17]:
player_features_df = pd.read_sql(query, con=engine)

In [18]:
print(player_features_df.head())
print(player_features_df.shape)

   player_id                   player_name  team_id  match_id  \
0      10958                Chris Smalling       39   3754015
1       6627  Damián Nicolás Suárez Suárez      216   3825817
2       5603             Nikola Milenković      786   3857256
3      26791                   Emir Spahić      171   3890360
4       8762              Zlatko Junuzović      176   3890285

   primary_position_id  position_event_count  role_group  total_passes  \
0                    3                  3711    Defender            51
1                    2                  5526    Defender            50
2                    3                   820    Defender            58
3                    5                  3998    Defender            60
4                   19                  1835  Midfielder            32

   completed_passes  progressive_passes  ...  goals_minus_xg  total_dribbles  \
0              43.0                18.0  ...           -0.13               0
1              35.0                17.0  ...            0.00               3
2              51.0                11.0  ...           -0.08               0
3              51.0                17.0  ...            0.00               0
4              19.0                 8.0  ...           -0.07               0

   successful_dribbles  dribble_success_rate  total_carries  \
0                  0.0                  0.00             40
1                  2.0                 66.67             27
2                  0.0                  0.00             46
3                  0.0                  0.00             40
4                  0.0                  0.00             21

   progressive_carries  total_duels  successful_duels  duel_success_rate  \
0                  7.0            2               0.0                0.0
1                  2.0            2               2.0              100.0
2                  3.0            4               2.0               50.0
3                  1.0            2               0.0                0.0
4                  2.0            4               2.0               50.0

   matches_played
0              35
1              40
2               9
3              28
4              30

[5 rows x 26 columns]
(97581, 26)

In [19]:
player_match_df = player_features_df.merge(player_minutes_df, on=["player_id", "team_id", "match_id"], how="inner")

In [20]:
print(player_match_df.shape)
print(player_match_df["minutes_played"].describe())
print(player_match_df.isna().sum())

(97545, 27)
count    97545.000000
mean        73.780624
std         29.329597
min          0.166667
25%         57.133333
50%         92.100000
75%         94.050000
max        127.633333
Name: minutes_played, dtype: float64
player_id                0
player_name              0
team_id                  0
match_id                 0
primary_position_id      0
position_event_count     0
role_group               0
total_passes             0
completed_passes         0
progressive_passes       0
pass_completion_rate     0
progressive_pass_rate    0
total_shots              0
goals                    0
total_xg                 0
average_xg_per_shot      0
goals_minus_xg           0
total_dribbles           0
successful_dribbles      0
dribble_success_rate     0
total_carries            0
progressive_carries      0
total_duels              0
successful_duels         0
duel_success_rate        0
matches_played           0
minutes_played           0
dtype: int64

In [21]:
player_match_df["passes_per_90"] = player_match_df["total_passes"] / player_match_df["minutes_played"] * 90
player_match_df["progressive_passes_per_90"] = player_match_df["progressive_passes"] / player_match_df["minutes_played"] * 90
player_match_df["shots_per_90"] = player_match_df["total_shots"] / player_match_df["minutes_played"] * 90
player_match_df["goals_per_90"] = player_match_df["goals"] / player_match_df["minutes_played"] * 90
player_match_df["xg_per_90"] = player_match_df["total_xg"] / player_match_df["minutes_played"] * 90
player_match_df["dribbles_per_90"] = player_match_df["total_dribbles"] / player_match_df["minutes_played"] * 90
player_match_df["carries_per_90"] = player_match_df["total_carries"] / player_match_df["minutes_played"] * 90
player_match_df["progressive_carries_per_90"] = player_match_df["progressive_carries"] / player_match_df["minutes_played"] * 90
player_match_df["duels_per_90"] = player_match_df["total_duels"] / player_match_df["minutes_played"] * 90
player_match_df["successful_duels_per_90"] = player_match_df["successful_duels"] / player_match_df["minutes_played"] * 90

In [22]:
player_match_df[["minutes_played", "passes_per_90", "progressive_passes_per_90", "shots_per_90", "dribbles_per_90", "carries_per_90", "duels_per_90"]].describe()

,minutes_played,passes_per_90,progressive_passes_per_90,shots_per_90,dribbles_per_90,carries_per_90,duels_per_90
count,97545.000000,97545.000000,97545.000000,97545.000000,97545.000000,97545.000000,97545.000000
mean,73.780624,41.679618,9.208052,1.235277,1.680190,33.230551,3.432549
std,29.329597,25.706619,7.631986,2.441311,2.750518,21.893941,4.021480
min,0.166667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,57.133333,26.199461,3.600000,0.000000,0.000000,19.474498,0.957617
50%,92.100000,37.721655,7.738607,0.000000,0.946704,29.948007,2.871831
75%,94.050000,53.061941,13.363974,1.911843,2.462380,42.970822,4.834378
max,127.633333,3240.000000,253.125000,337.500000,110.204082,2700.000000,540.000000

In [23]:
training_player_match_df = player_match_df[player_match_df["minutes_played"] >= 20].copy()
print(training_player_match_df.shape)
print(training_player_match_df[["minutes_played", "passes_per_90", "progressive_passes_per_90", "shots_per_90", "dribbles_per_90", "carries_per_90", "duels_per_90"]].describe())

(88513, 37)
       minutes_played  passes_per_90  progressive_passes_per_90  shots_per_90  \
count    88513.000000   88513.000000               88513.000000  88513.000000
mean        80.063605      41.937342                   9.489712      1.163867
std         22.786250      20.710296                   7.259441      1.686568
min         20.000000       0.000000                   0.000000      0.000000
25%         70.300000      26.907216                   3.866118      0.000000
50%         92.983333      38.145264                   8.148893      0.000000
75%         94.100000      53.159119                  13.466334      1.913876
max        127.633333     214.914573                  67.278689     22.500000

       dribbles_per_90  carries_per_90  duels_per_90
count     88513.000000    88513.000000  88513.000000
mean          1.613861       33.110495      3.298838
std           2.266704       18.374004      2.811567
min           0.000000        0.000000      0.000000
25%           0.000000       19.971821      0.984862
50%           0.956768       29.989251      2.883075
75%           2.488479       42.612889      4.788083
max          28.463855      178.457772     36.860068

In [24]:
training_player_match_df = player_match_df[player_match_df["minutes_played"] >= 20].copy()

In [25]:
print(training_player_match_df["player_id"].nunique())
print(training_player_match_df["matches_played"].describe())

8488
count    88513.000000
mean        41.529436
std         68.982304
min          1.000000
25%         15.000000
50%         29.000000
75%         39.000000
max        603.000000
Name: matches_played, dtype: float64

In [26]:
autoencoder_features = ["passes_per_90", "pass_completion_rate", "progressive_passes_per_90", "progressive_pass_rate", "carries_per_90", "progressive_carries_per_90", "dribbles_per_90", "dribble_success_rate", "shots_per_90", "goals_per_90", "xg_per_90", "average_xg_per_shot", "duels_per_90", "successful_duels_per_90", "duel_success_rate"]
autoencoder_features_df = training_player_match_df[autoencoder_features].copy()
print(autoencoder_features_df.shape)
print(autoencoder_features_df.isna().sum())
print(np.isinf(autoencoder_features_df).sum())

(88513, 15)
passes_per_90                 0
pass_completion_rate          0
progressive_passes_per_90     0
progressive_pass_rate         0
carries_per_90                0
progressive_carries_per_90    0
dribbles_per_90               0
dribble_success_rate          0
shots_per_90                  0
goals_per_90                  0
xg_per_90                     0
average_xg_per_shot           0
duels_per_90                  0
successful_duels_per_90       0
duel_success_rate             0
dtype: int64
passes_per_90                 0
pass_completion_rate          0
progressive_passes_per_90     0
progressive_pass_rate         0
carries_per_90                0
progressive_carries_per_90    0
dribbles_per_90               0
dribble_success_rate          0
shots_per_90                  0
goals_per_90                  0
xg_per_90                     0
average_xg_per_shot           0
duels_per_90                  0
successful_duels_per_90       0
duel_success_rate             0
dtype: int64

In [27]:
scaler = StandardScaler()
scaled_features = scaler.fit_transform(autoencoder_features_df)
scaled_features_df = pd.DataFrame(scaled_features, columns = autoencoder_features, index=training_player_match_df.index)

In [28]:
print(scaled_features_df.shape)
print(scaled_features_df.mean().round(3))
print(scaled_features_df.std().round(3))

(88513, 15)
passes_per_90                 0.0
pass_completion_rate         -0.0
progressive_passes_per_90    -0.0
progressive_pass_rate        -0.0
carries_per_90                0.0
progressive_carries_per_90   -0.0
dribbles_per_90               0.0
dribble_success_rate          0.0
shots_per_90                 -0.0
goals_per_90                 -0.0
xg_per_90                    -0.0
average_xg_per_shot          -0.0
duels_per_90                 -0.0
successful_duels_per_90      -0.0
duel_success_rate            -0.0
dtype: float64
passes_per_90                 1.0
pass_completion_rate          1.0
progressive_passes_per_90     1.0
progressive_pass_rate         1.0
carries_per_90                1.0
progressive_carries_per_90    1.0
dribbles_per_90               1.0
dribble_success_rate          1.0
shots_per_90                  1.0
goals_per_90                  1.0
xg_per_90                     1.0
average_xg_per_shot           1.0
duels_per_90                  1.0
successful_duels_per_90       1.0
duel_success_rate             1.0
dtype: float64

In [29]:
unique_players = training_player_match_df["player_id"].unique()
train_players, val_players = train_test_split(unique_players, test_size=0.2, random_state=42)

In [30]:
train_df = training_player_match_df[training_player_match_df["player_id"].isin(train_players)].copy()
val_df = training_player_match_df[training_player_match_df["player_id"].isin(val_players)].copy()

In [31]:
X_train = train_df[autoencoder_features].copy()
X_val = val_df[autoencoder_features].copy()

In [32]:
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

In [33]:
print(train_df["player_id"].nunique(), val_df["player_id"].nunique())
print(X_train_scaled.shape, X_val_scaled.shape)
print(set(train_df["player_id"]).intersection(set(val_df["player_id"])))

6790 1698
(70877, 15) (17636, 15)
set()

In [34]:
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
X_val_tensor = torch.tensor(X_val_scaled, dtype=torch.float32)

print(X_train_tensor.shape)
print(X_val_tensor.shape)

torch.Size([70877, 15])
torch.Size([17636, 15])

In [35]:
random.seed(42)
np.random.seed(42)
torch.manual_seed(42)

In [36]:
class Autoencoder(nn.Module):
    def __init__(self):
        super().__init__()

        self.encoder = nn.Sequential(nn.Linear(15, 10), nn.ReLU(), nn.Linear(10, 5))
        self.decoder = nn.Sequential(nn.Linear(5, 10), nn.ReLU(), nn.Linear(10, 15))

    def forward(self, x):
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        return decoded

In [37]:
model = Autoencoder()
model

Autoencoder(
  (encoder): Sequential(
    (0): Linear(in_features=15, out_features=10, bias=True)
    (1): ReLU()
    (2): Linear(in_features=10, out_features=5, bias=True)
  )
  (decoder): Sequential(
    (0): Linear(in_features=5, out_features=10, bias=True)
    (1): ReLU()
    (2): Linear(in_features=10, out_features=15, bias=True)
  )
)

In [38]:
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [39]:
num_epochs = 150

for epoch in range(num_epochs):
    model.train()

    optimizer.zero_grad()
    reconstructed = model(X_train_tensor)
    loss = criterion(reconstructed, X_train_tensor)
    loss.backward()
    optimizer.step()

    model.eval()

    with torch.no_grad():
        val_reconstructed = model(X_val_tensor)
        val_loss = criterion(val_reconstructed, X_val_tensor)

    if (epoch + 1) % 5 == 0:
        print(f"Epoch {epoch + 1}/{num_epochs}, Train Loss: {loss.item():.4f}, Val Loss: {val_loss.item():.4f}")

Epoch 5/150, Train Loss: 1.0558, Val Loss: 1.0197
Epoch 10/150, Train Loss: 1.0439, Val Loss: 1.0080
Epoch 15/150, Train Loss: 1.0328, Val Loss: 0.9970
Epoch 20/150, Train Loss: 1.0222, Val Loss: 0.9864
Epoch 25/150, Train Loss: 1.0119, Val Loss: 0.9762
Epoch 30/150, Train Loss: 1.0019, Val Loss: 0.9663
Epoch 35/150, Train Loss: 0.9921, Val Loss: 0.9564
Epoch 40/150, Train Loss: 0.9821, Val Loss: 0.9464
Epoch 45/150, Train Loss: 0.9717, Val Loss: 0.9360
Epoch 50/150, Train Loss: 0.9608, Val Loss: 0.9250
Epoch 55/150, Train Loss: 0.9489, Val Loss: 0.9131
Epoch 60/150, Train Loss: 0.9360, Val Loss: 0.9002
Epoch 65/150, Train Loss: 0.9218, Val Loss: 0.8862
Epoch 70/150, Train Loss: 0.9062, Val Loss: 0.8707
Epoch 75/150, Train Loss: 0.8892, Val Loss: 0.8539
Epoch 80/150, Train Loss: 0.8707, Val Loss: 0.8357
Epoch 85/150, Train Loss: 0.8508, Val Loss: 0.8163
Epoch 90/150, Train Loss: 0.8297, Val Loss: 0.7960
Epoch 95/150, Train Loss: 0.8079, Val Loss: 0.7750
Epoch 100/150, Train Loss: 0.7856, Val Loss: 0.7538
Epoch 105/150, Train Loss: 0.7633, Val Loss: 0.7328
Epoch 110/150, Train Loss: 0.7414, Val Loss: 0.7123
Epoch 115/150, Train Loss: 0.7203, Val Loss: 0.6926
Epoch 120/150, Train Loss: 0.7001, Val Loss: 0.6739
Epoch 125/150, Train Loss: 0.6809, Val Loss: 0.6562
Epoch 130/150, Train Loss: 0.6629, Val Loss: 0.6394
Epoch 135/150, Train Loss: 0.6459, Val Loss: 0.6236
Epoch 140/150, Train Loss: 0.6300, Val Loss: 0.6087
Epoch 145/150, Train Loss: 0.6151, Val Loss: 0.5947
Epoch 150/150, Train Loss: 0.6012, Val Loss: 0.5815

In [40]:
train_dataset = TensorDataset(X_train_tensor)
val_dataset = TensorDataset(X_val_tensor)

train_loader = DataLoader(train_dataset, batch_size=256, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=256, shuffle=False)

In [41]:
model = Autoencoder()
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [42]:
num_epochs = 150
patience = 10
best_val_loss = float('inf')
epochs_without_improvement = 0
best_model_state = None
train_losses = []
val_losses = []

for epoch in range(num_epochs):
    model.train()
    train_loss = 0

    for (batch,) in train_loader:
        optimizer.zero_grad()
        reconstructed = model(batch)
        loss = criterion(reconstructed, batch)
        loss.backward()
        optimizer.step()
        train_loss += loss.item() * batch.size(0)

    train_loss /= len(train_dataset)
    train_losses.append(train_loss)

    model.eval()
    val_loss = 0

    with torch.no_grad():
        for (batch,) in val_loader:
            reconstructed = model(batch)
            loss = criterion(reconstructed, batch)
            val_loss += loss.item() * batch.size(0)

        val_loss /= len(val_dataset)
        val_losses.append(val_loss)

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_model_state = copy.deepcopy(model.state_dict())
        epochs_without_improvement = 0

    else:
        epochs_without_improvement += 1

    if (epoch + 1) % 5 == 0:
        print(f"Epoch {epoch + 1}/{num_epochs}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}")

    if epochs_without_improvement >= patience:
        print(f"Early stopping at epoch {epoch + 1}")
        break

model.load_state_dict(best_model_state)
print(f"Best validation loss: {best_val_loss:.4f}")

Epoch 5/150, Train Loss: 0.2362, Val Loss: 0.2212
Epoch 10/150, Train Loss: 0.1995, Val Loss: 0.1938
Epoch 15/150, Train Loss: 0.1899, Val Loss: 0.1852
Epoch 20/150, Train Loss: 0.1860, Val Loss: 0.1816
Epoch 25/150, Train Loss: 0.1841, Val Loss: 0.1797
Epoch 30/150, Train Loss: 0.1822, Val Loss: 0.1778
Epoch 35/150, Train Loss: 0.1803, Val Loss: 0.1764
Epoch 40/150, Train Loss: 0.1789, Val Loss: 0.1752
Epoch 45/150, Train Loss: 0.1779, Val Loss: 0.1742
Epoch 50/150, Train Loss: 0.1771, Val Loss: 0.1739
Epoch 55/150, Train Loss: 0.1764, Val Loss: 0.1726
Epoch 60/150, Train Loss: 0.1755, Val Loss: 0.1729
Epoch 65/150, Train Loss: 0.1744, Val Loss: 0.1706
Epoch 70/150, Train Loss: 0.1732, Val Loss: 0.1699
Epoch 75/150, Train Loss: 0.1725, Val Loss: 0.1692
Epoch 80/150, Train Loss: 0.1719, Val Loss: 0.1684
Epoch 85/150, Train Loss: 0.1715, Val Loss: 0.1676
Epoch 90/150, Train Loss: 0.1711, Val Loss: 0.1672
Epoch 95/150, Train Loss: 0.1707, Val Loss: 0.1674
Epoch 100/150, Train Loss: 0.1704, Val Loss: 0.1669
Epoch 105/150, Train Loss: 0.1701, Val Loss: 0.1663
Epoch 110/150, Train Loss: 0.1697, Val Loss: 0.1660
Epoch 115/150, Train Loss: 0.1693, Val Loss: 0.1656
Epoch 120/150, Train Loss: 0.1691, Val Loss: 0.1657
Early stopping at epoch 122
Best validation loss: 0.1654

In [43]:
model.eval()

with torch.no_grad():
    val_embeddings = model.encoder(X_val_tensor)

print(val_embeddings.shape)
print(val_embeddings[:5])

torch.Size([17636, 5])
tensor([[ 8.6413,  2.9807, 16.5143, -5.8373,  0.5802],
        [ 4.1991,  1.1132,  7.6930, -4.8802,  0.2359],
        [ 1.7147,  0.2072, -1.1085, -2.2994,  1.3278],
        [ 5.6141, -0.1899, -2.6952, -4.2151,  2.6758],
        [ 1.8503,  0.3794, -0.1946, -3.3635,  1.2373]])

In [44]:
val_embeddings_df = val_df[["player_id", "player_name", "team_id", "match_id", "role_group"]].copy()
val_embeddings_df[["latent_1", "latent_2", "latent_3", "latent_4", "latent_5"]] = val_embeddings.numpy()

In [45]:
player_embeddings_df = val_embeddings_df.groupby(["player_id", "player_name", "role_group"], as_index=False)[["latent_1", "latent_2", "latent_3", "latent_4", "latent_5"]].mean()

print(player_embeddings_df.shape)
player_embeddings_df.head()

(1698, 8)

,player_id,player_name,role_group,latent_1,latent_2,latent_3,latent_4,latent_5
0,2954,Youri Tielemans,Midfielder,2.694586,1.057221,0.464098,-4.872576,1.203533
1,2963,Rémy Vercoutre,Goalkeeper,0.061896,-0.565476,-1.073689,-2.196335,0.726832
2,2968,Elias Kachunga,Forward,5.808084,-0.286076,-1.941710,-1.749292,2.167019
3,2970,Christian Kouakou Yao,Forward,1.097620,1.700708,0.064506,-2.030886,-0.374848
4,2974,Saîf-Eddine Khaoui,Midfielder,0.510237,0.449534,-0.139571,-1.837117,0.165013

In [46]:
all_features_tensor = torch.tensor(scaled_features_df.to_numpy(), dtype=torch.float32)
print(type(scaled_features_df))
print(type(all_features_tensor))
print(all_features_tensor.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'torch.Tensor'>
torch.Size([88513, 15])

In [47]:
model.eval()

with torch.no_grad():
    all_embeddings = model.encoder(all_features_tensor)

print(all_embeddings.shape)

torch.Size([88513, 5])

In [48]:
all_embeddings_df = training_player_match_df[["player_id", "player_name", "team_id", "match_id", "role_group"]].copy()
all_embeddings_df[["latent_1", "latent_2", "latent_3", "latent_4", "latent_5"]] = all_embeddings.numpy()

In [49]:
print(all_embeddings_df.shape)
print(all_embeddings.shape)
all_embeddings_df.head()

(88513, 10)
torch.Size([88513, 5])

,player_id,player_name,team_id,match_id,role_group,latent_1,latent_2,latent_3,latent_4,latent_5
0,10958,Chris Smalling,39,3754015,Defender,1.443607,-0.583997,0.569966,-3.451158,0.453443
1,6627,Damián Nicolás Suárez Suárez,216,3825817,Defender,0.208751,1.149550,-1.212804,-4.764975,0.577066
2,5603,Nikola Milenković,786,3857256,Defender,1.188555,0.877760,0.628151,-3.291087,0.522931
3,26791,Emir Spahić,171,3890360,Defender,2.417922,-0.744307,-0.089657,-3.131258,1.161113
4,8762,Zlatko Junuzović,176,3890285,Midfielder,1.462781,0.987995,-0.906270,-2.172323,1.286313

In [50]:
player_train_embeddings_df = all_embeddings_df.groupby(["player_id", "player_name", "role_group"], as_index=False)[["latent_1", "latent_2", "latent_3", "latent_4", "latent_5"]].mean()

print(player_train_embeddings_df.shape)
player_train_embeddings_df.head()

(8488, 8)

,player_id,player_name,role_group,latent_1,latent_2,latent_3,latent_4,latent_5
0,2935,Nordi Mukiele Mulere,Defender,2.341134,0.129685,-0.040444,-3.328264,0.873233
1,2936,Christophe Kerbrat,Defender,2.944760,0.168735,-1.070610,-2.926457,1.931874
2,2937,Christ-Emmanuel Faitout Maouassa,Defender,0.802602,1.880460,-0.366159,-2.893295,0.068362
3,2941,Ismaïla Sarr,Forward,2.017413,1.010464,1.350277,-2.629025,-0.622341
4,2943,Lucas Deaux,Defender,3.560570,-0.016519,-1.400836,-3.980598,2.256700

In [51]:
xavi_embedding = player_train_embeddings_df[player_train_embeddings_df["player_id"] == 20131]
xavi_embedding

,player_id,player_name,role_group,latent_1,latent_2,latent_3,latent_4,latent_5
3826,20131,Xavier Hernández Creus,Midfielder,3.478941,-0.140268,1.990323,-7.222062,0.458527

In [52]:
midfielder_embeddings_df = player_train_embeddings_df[player_train_embeddings_df["role_group"] == "Midfielder"].copy()

latent_features = ["latent_1", "latent_2", "latent_3", "latent_4", "latent_5"]

In [53]:
from sklearn.neighbors import NearestNeighbors

knn = NearestNeighbors(n_neighbors=11, metric="euclidean")
knn.fit(midfielder_embeddings_df[latent_features])

xavi_index = midfielder_embeddings_df.index[midfielder_embeddings_df["player_id"] == 20131][0]
xavi_position = midfielder_embeddings_df.index.get_loc(xavi_index)

distances, indices = knn.kneighbors(midfielder_embeddings_df[latent_features].iloc[[xavi_position]])

xavi_neighbors = midfielder_embeddings_df.iloc[indices[0]].copy()
xavi_neighbors["distance"] = distances[0]

xavi_neighbors = xavi_neighbors[xavi_neighbors["player_id"] != 20131]
xavi_neighbors[["player_id", "player_name", "role_group", "distance"]].head(10)

      player_id                  player_name  role_group  distance
639        4370        Javier Matías Pastore  Midfielder  1.106996
1022       5216         Andrés Iniesta Luján  Midfielder  1.497109
2579       9475               Moritz Leitner  Midfielder  1.564192
5544      28268  Exequiel Alejandro Palacios  Midfielder  1.597300
2770      10287               İlkay Gündoğan  Midfielder  1.659098
351        3478    Francesc Fàbregas i Soler  Midfielder  1.684171
1849       7025                 Marek Hamšík  Midfielder  1.710404
701        4544          Jeff Reine-Adélaïde  Midfielder  1.760512
1083       5463                  Luka Modrić  Midfielder  1.761913
428        3593    Renato Júnior Luz Sanches  Midfielder  1.867097

In [54]:
player_profile_df = training_player_match_df.groupby(["player_id", "player_name", "role_group"], as_index=False)[autoencoder_features].mean()

neighbor_ids = xavi_neighbors["player_id"].tolist()
comparison_ids = [20131] + neighbor_ids

xavi_comparison_df = player_profile_df[player_profile_df["player_id"].isin(comparison_ids)].copy()

xavi_comparison_df

,player_id,player_name,role_group,passes_per_90,pass_completion_rate,progressive_passes_per_90,progressive_pass_rate,carries_per_90,progressive_carries_per_90,dribbles_per_90,dribble_success_rate,shots_per_90,goals_per_90,xg_per_90,average_xg_per_shot,duels_per_90,successful_duels_per_90,duel_success_rate
351,3478,Francesc Fàbregas i Soler,Midfielder,86.192866,84.273451,20.418332,23.419823,72.870593,5.361918,1.956967,50.693274,1.658678,0.261471,0.186657,0.077345,3.639673,1.490972,39.780000
428,3593,Renato Júnior Luz Sanches,Midfielder,74.836488,90.911765,14.598223,19.196471,71.037745,7.137877,2.260531,33.921765,1.460452,0.174627,0.090677,0.031176,1.485785,1.012162,27.451176
639,4370,Javier Matías Pastore,Midfielder,91.995346,78.338571,21.108346,22.555714,80.385118,9.759042,3.218105,53.869286,2.274625,0.157595,0.342657,0.100000,2.291366,1.132146,39.285000
701,4544,Jeff Reine-Adélaïde,Midfielder,71.760797,81.250000,22.425249,31.250000,67.275748,22.425249,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1022,5216,Andrés Iniesta Luján,Midfielder,75.320665,87.719180,16.913579,22.239338,74.459952,7.334254,4.412124,62.404763,1.405466,0.100213,0.118730,0.052871,2.296250,1.244662,42.393975
1083,5463,Luka Modrić,Midfielder,69.356483,86.686812,18.929345,27.123768,58.950736,5.772955,2.118485,57.180725,1.119874,0.169746,0.125261,0.071304,2.163192,0.918074,38.236667
1849,7025,Marek Hamšík,Midfielder,82.527454,84.890976,16.786651,19.821951,66.167923,7.742515,1.236305,36.788537,2.225120,0.150308,0.169279,0.065854,2.409230,0.804197,31.730244
2579,9475,Moritz Leitner,Midfielder,88.081936,86.525000,20.526876,18.833333,83.820780,8.206552,2.830648,41.666667,1.802550,0.000000,0.069228,0.020000,2.243007,1.287966,38.888333
2770,10287,İlkay Gündoğan,Midfielder,79.597408,87.042973,17.955840,21.340811,70.354974,5.476267,2.154930,47.567297,2.016763,0.117778,0.183609,0.070000,2.270666,1.022764,39.111892
3826,20131,Xavier Hernández Creus,Midfielder,101.215979,88.980080,24.736060,24.299721,87.612910,6.827732,1.858556,59.498287,1.357238,0.145655,0.106563,0.055458,1.682310,0.873470,38.658685
5544,28268,Exequiel Alejandro Palacios,Midfielder,90.323127,91.679200,15.652096,17.106000,77.253134,2.788943,0.965638,48.000000,0.868599,0.197499,0.126796,0.068000,3.375617,1.918745,52.943200

In [55]:
midfielder_profiles_df = player_profile_df[player_profile_df["role_group"] == "Midfielder"].copy()
profile_scaler = StandardScaler()
scaled_midfielder_profiles = profile_scaler.fit_transform(midfielder_profiles_df[autoencoder_features])
scaled_midfielder_profiles_df = pd.DataFrame(scaled_midfielder_profiles, columns=autoencoder_features, index = midfielder_profiles_df.index)

In [56]:
xavi_profile = scaled_midfielder_profiles_df.loc[midfielder_profiles_df["player_id"] == 20131].iloc[0]

neighbor_ids = xavi_neighbors["player_id"].tolist()
neighbor_profiles = scaled_midfielder_profiles_df.loc[midfielder_profiles_df["player_id"].isin(neighbor_ids)].copy()

feature_differences = neighbor_profiles.sub(xavi_profile).abs()
feature_differences["player_name"] = midfielder_profiles_df.loc[feature_differences.index, "player_name"]

feature_differences[["player_name"] + autoencoder_features].head(10)

,player_name,passes_per_90,pass_completion_rate,progressive_passes_per_90,progressive_pass_rate,carries_per_90,progressive_carries_per_90,dribbles_per_90,dribble_success_rate,shots_per_90,goals_per_90,xg_per_90,average_xg_per_shot,duels_per_90,successful_duels_per_90,duel_success_rate
351,Francesc Fàbregas i Soler,0.998597,0.420726,0.922227,0.111204,1.150071,0.559951,0.054747,0.311334,0.262316,0.470833,0.509674,0.394169,0.966263,0.532042,0.044678
428,Renato Júnior Luz Sanches,1.753464,0.172674,2.165349,0.644964,1.293054,0.118478,0.223626,0.904354,0.089818,0.117782,0.101094,0.437297,0.097016,0.119498,0.446559
639,Javier Matías Pastore,0.612902,0.951246,0.774846,0.220413,0.563851,1.119781,0.756343,0.199035,0.798320,0.048539,1.502376,0.802168,0.300664,0.222876,0.024955
701,Jeff Reine-Adélaïde,1.957907,0.690993,0.493568,0.878396,1.586534,5.958361,1.033951,2.103786,1.181084,0.592136,0.678113,0.998764,0.830482,0.752585,1.540339
1022,Andrés Iniesta Luján,1.721280,0.112712,1.670810,0.260397,1.026083,0.193495,1.420599,0.102769,0.041968,0.184737,0.077424,0.046599,0.303075,0.319820,0.148831
1083,Luka Modrić,2.117724,0.204996,1.240261,0.356911,2.235981,0.402932,0.144603,0.081946,0.206557,0.097940,0.118984,0.285379,0.237390,0.038431,0.016815
1849,Marek Hamšík,1.242240,0.365526,1.697921,0.565914,1.672957,0.349454,0.346170,0.802989,0.755240,0.018915,0.399090,0.187216,0.358848,0.059686,0.276061
2579,Moritz Leitner,0.873029,0.219460,0.899043,0.690858,0.295830,0.526719,0.540793,0.630504,0.387515,0.592136,0.237580,0.638577,0.276791,0.357131,0.009150
2770,İlkay Gündoğan,1.437002,0.173158,1.448193,0.373956,1.346319,0.516269,0.164878,0.421865,0.573926,0.113331,0.490280,0.261889,0.290445,0.128632,0.018058
5544,Exequiel Alejandro Palacios,0.724056,0.241275,1.940251,0.909163,0.808182,1.542845,0.496748,0.406565,0.425219,0.210764,0.128749,0.225870,0.835911,0.900612,0.569161

In [58]:
player = feature_differences.iloc[0]
feature_values = player[autoencoder_features].astype(float)

closest_features = feature_values.nsmallest(3)
furthest_features = feature_values.nlargest(3)

print(player["player_name"])
print("Most similar:")
print(closest_features)

print("\nMost different:")
print(furthest_features)

Francesc Fàbregas i Soler
Most similar:
duel_success_rate        0.044678
dribbles_per_90          0.054747
progressive_pass_rate    0.111204
Name: 351, dtype: float64

Most different:
carries_per_90    1.150071
passes_per_90     0.998597
duels_per_90      0.966263
Name: 351, dtype: float64

In [62]:
for index, row in feature_differences.iterrows():

    feature_values = row[autoencoder_features].astype(float)

    closest_features = feature_values.nsmallest(3)
    furthest_features = feature_values.nlargest(3)

    print(row["player_name"])
    print("Most similar:")
    print(closest_features)

    print("Most different:")
    print(furthest_features)
    print()

Francesc Fàbregas i Soler
Most similar:
duel_success_rate        0.044678
dribbles_per_90          0.054747
progressive_pass_rate    0.111204
Name: 351, dtype: float64
Most different:
carries_per_90    1.150071
passes_per_90     0.998597
duels_per_90      0.966263
Name: 351, dtype: float64

Renato Júnior Luz Sanches
Most similar:
shots_per_90    0.089818
duels_per_90    0.097016
xg_per_90       0.101094
Name: 428, dtype: float64
Most different:
progressive_passes_per_90    2.165349
passes_per_90                1.753464
carries_per_90               1.293054
Name: 428, dtype: float64

Javier Matías Pastore
Most similar:
duel_success_rate       0.024955
goals_per_90            0.048539
dribble_success_rate    0.199035
Name: 639, dtype: float64
Most different:
xg_per_90                     1.502376
progressive_carries_per_90    1.119781
pass_completion_rate          0.951246
Name: 639, dtype: float64

Jeff Reine-Adélaïde
Most similar:
progressive_passes_per_90    0.493568
goals_per_90                 0.592136
xg_per_90                    0.678113
Name: 701, dtype: float64
Most different:
progressive_carries_per_90    5.958361
dribble_success_rate          2.103786
passes_per_90                 1.957907
Name: 701, dtype: float64

Andrés Iniesta Luján
Most similar:
shots_per_90           0.041968
average_xg_per_shot    0.046599
xg_per_90              0.077424
Name: 1022, dtype: float64
Most different:
passes_per_90                1.721280
progressive_passes_per_90    1.670810
dribbles_per_90              1.420599
Name: 1022, dtype: float64

Luka Modrić
Most similar:
duel_success_rate          0.016815
successful_duels_per_90    0.038431
dribble_success_rate       0.081946
Name: 1083, dtype: float64
Most different:
carries_per_90               2.235981
passes_per_90                2.117724
progressive_passes_per_90    1.240261
Name: 1083, dtype: float64

Marek Hamšík
Most similar:
goals_per_90               0.018915
successful_duels_per_90    0.059686
average_xg_per_shot        0.187216
Name: 1849, dtype: float64
Most different:
progressive_passes_per_90    1.697921
carries_per_90               1.672957
passes_per_90                1.242240
Name: 1849, dtype: float64

Moritz Leitner
Most similar:
duel_success_rate       0.00915
pass_completion_rate    0.21946
xg_per_90               0.23758
Name: 2579, dtype: float64
Most different:
progressive_passes_per_90    0.899043
passes_per_90                0.873029
progressive_pass_rate        0.690858
Name: 2579, dtype: float64

İlkay Gündoğan
Most similar:
duel_success_rate          0.018058
goals_per_90               0.113331
successful_duels_per_90    0.128632
Name: 2770, dtype: float64
Most different:
progressive_passes_per_90    1.448193
passes_per_90                1.437002
carries_per_90               1.346319
Name: 2770, dtype: float64

Exequiel Alejandro Palacios
Most similar:
xg_per_90              0.128749
goals_per_90           0.210764
average_xg_per_shot    0.225870
Name: 5544, dtype: float64
Most different:
progressive_passes_per_90     1.940251
progressive_carries_per_90    1.542845
progressive_pass_rate         0.909163
Name: 5544, dtype: float64

In [64]:
from sklearn.decomposition import PCA
from sklearn.metrics import mean_squared_error

pca = PCA(n_components=5)
pca_train = pca.fit(X_train_scaled)
pca_val = pca.transform(X_val_scaled)
X_val_reconstructed = pca.inverse_transform(pca_val)
pca_reconstruction_mse = mean_squared_error(X_val_scaled, X_val_reconstructed)
print("PCA validation reconstruction MSE: ", pca_reconstruction_mse)

PCA validation reconstruction MSE:  0.26467194099375824

In [66]:
autoencoder_mse = 0.1654
reconstruction_improvement = (pca_reconstruction_mse - autoencoder_mse)/pca_reconstruction_mse * 100
print(f"Autoencoder reconstruction MSE improvement over PCA: {reconstruction_improvement:.2f}%")

Autoencoder reconstruction MSE improvement over PCA: 37.51%

In [67]:
player_profile_df["role_group"].value_counts()

role_group
Defender      3049
Midfielder    2724
Forward       2045
Goalkeeper     670
Name: count, dtype: int64

In [68]:
from sklearn.neighbors import NearestNeighbors

evaluation_features = player_profile_df[autoencoder_features]
evaluation_scaler = StandardScaler()
evaluation_scaler.fit(evaluation_features)
evaluation_scaled_features = evaluation_scaler.transform(evaluation_features)

In [69]:
euclidean_knn = NearestNeighbors(n_neighbors=11, metric="euclidean")
euclidean_knn.fit(evaluation_scaled_features)

distances, indices = euclidean_knn.kneighbors(evaluation_scaled_features)

In [70]:
print(distances.shape)
print(indices.shape)
print(distances[0])
print(indices[0])

(8488, 11)
(8488, 11)
[0.         1.04222671 1.07141651 1.09939738 1.11867053 1.13185037
 1.13895105 1.14023368 1.15783788 1.1634385  1.16948716]
[   0 4586 2043 1819 3584 1125 4278 5864 1918 1886  218]

In [71]:
neighbor_indices = indices[:, 1:]

target_role = player_profile_df.iloc[0]["role_group"]
neighbor_roles = player_profile_df.iloc[neighbor_indices[0]]["role_group"]

print("Target:", player_profile_df.iloc[0]["player_name"])
print("Target role:", target_role)
print("\nNeighbor roles:")
print(neighbor_roles)

Target: Nordi Mukiele Mulere
Target role: Defender

Neighbor roles:
4586      Defender
2043      Defender
1819      Defender
3584      Defender
1125      Defender
4278    Midfielder
5864      Defender
1918    Midfielder
1886    Midfielder
218     Midfielder
Name: role_group, dtype: object

In [81]:
role_coherence = (neighbor_roles == target_role).mean()
role_coherence

np.float64(0.6)

In [82]:
role_coherence_scores = []
for i in range(len(player_profile_df)):
    target_role = player_profile_df.iloc[i]["role_group"]
    neighbor_roles = player_profile_df.iloc[neighbor_indices[i]]["role_group"]

    coherence = (neighbor_roles == target_role).mean()
    role_coherence_scores.append(coherence)

euclidean_role_coherence = np.mean(role_coherence_scores)

print(f"Euclidean role coherence@10: {euclidean_role_coherence:.2%}")

Euclidean role coherence@10: 66.26%

In [83]:
role_counts = player_profile_df["role_group"].value_counts()
total_players = len(player_profile_df)

In [85]:
random_role_coherence = 0

for count in role_counts:
    role_probabibility = count/total_players
    same_role_probability = (count - 1) / (total_players - 1)
    
    contribution = role_probabibility * same_role_probability
    random_role_coherence += contribution

print(f"Random role coherence: {random_role_coherence:.2%}")

Random role coherence: 29.62%

In [86]:
cosine_knn = NearestNeighbors(n_neighbors=11, metric="cosine")
cosine_knn.fit(evaluation_scaled_features)

cosine_distances, cosine_indices = cosine_knn.kneighbors(evaluation_scaled_features)

# Remove each player themselves from the retrieved neighbors
cosine_neighbor_indices = cosine_indices[:, 1:]

# Calculate role coherence@10 for every player
cosine_role_coherence_scores = []

for i in range(len(player_profile_df)):
    target_role = player_profile_df.iloc[i]["role_group"]
    neighbor_roles = player_profile_df.iloc[cosine_neighbor_indices[i]]["role_group"]

    coherence = (neighbor_roles == target_role).mean()
    cosine_role_coherence_scores.append(coherence)

cosine_role_coherence = np.mean(cosine_role_coherence_scores)

print(f"Random role coherence@10: {random_role_coherence:.2%}")
print(f"Euclidean role coherence@10: {euclidean_role_coherence:.2%}")
print(f"Cosine role coherence@10: {cosine_role_coherence:.2%}")

Random role coherence@10: 29.62%
Euclidean role coherence@10: 66.26%
Cosine role coherence@10: 65.17%

In [87]:
pca_evaluation = PCA(n_components=5)
pca_evaluation_features = pca_evaluation.fit_transform(evaluation_scaled_features)

pca_knn = NearestNeighbors(n_neighbors=11, metric="euclidean")
pca_knn.fit(pca_evaluation_features)

pca_distances, pca_indices = pca_knn.kneighbors(pca_evaluation_features)
pca_neighbor_indices = pca_indices[:, 1:]

pca_role_coherence_scores = []

for i in range(len(player_profile_df)):
    target_role = player_profile_df.iloc[i]["role_group"]
    neighbor_roles = player_profile_df.iloc[pca_neighbor_indices[i]]["role_group"]

    coherence = (neighbor_roles == target_role).mean()
    pca_role_coherence_scores.append(coherence)

pca_role_coherence = np.mean(pca_role_coherence_scores)

print(f"Random role coherence@10: {random_role_coherence:.2%}")
print(f"Euclidean role coherence@10: {euclidean_role_coherence:.2%}")
print(f"Cosine role coherence@10: {cosine_role_coherence:.2%}")
print(f"PCA role coherence@10: {pca_role_coherence:.2%}")

Random role coherence@10: 29.62%
Euclidean role coherence@10: 66.26%
Cosine role coherence@10: 65.17%
PCA role coherence@10: 63.10%

In [88]:
print(player_train_embeddings_df.shape)
print(player_train_embeddings_df.columns)
print(player_train_embeddings_df["role_group"].value_counts())

(8488, 8)
Index(['player_id', 'player_name', 'role_group', 'latent_1', 'latent_2',
       'latent_3', 'latent_4', 'latent_5'],
      dtype='object')
role_group
Defender      3049
Midfielder    2724
Forward       2045
Goalkeeper     670
Name: count, dtype: int64

In [89]:
latent_features = ["latent_1", "latent_2", "latent_3", "latent_4", "latent_5"]

autoencoder_evaluation_features = player_train_embeddings_df[latent_features].values

autoencoder_knn = NearestNeighbors(n_neighbors=11, metric="euclidean")
autoencoder_knn.fit(autoencoder_evaluation_features)

autoencoder_distances, autoencoder_indices = autoencoder_knn.kneighbors(autoencoder_evaluation_features)
autoencoder_neighbor_indices = autoencoder_indices[:, 1:]

autoencoder_role_coherence_scores = []

for i in range(len(player_train_embeddings_df)):
    target_role = player_train_embeddings_df.iloc[i]["role_group"]
    neighbor_roles = player_train_embeddings_df.iloc[autoencoder_neighbor_indices[i]]["role_group"]

    coherence = (neighbor_roles == target_role).mean()
    autoencoder_role_coherence_scores.append(coherence)

autoencoder_role_coherence = np.mean(autoencoder_role_coherence_scores)

print(f"Random role coherence@10:      {random_role_coherence:.2%}")
print(f"Euclidean role coherence@10:   {euclidean_role_coherence:.2%}")
print(f"Cosine role coherence@10:      {cosine_role_coherence:.2%}")
print(f"PCA role coherence@10:         {pca_role_coherence:.2%}")
print(f"Autoencoder role coherence@10: {autoencoder_role_coherence:.2%}")

Random role coherence@10:      29.62%
Euclidean role coherence@10:   66.26%
Cosine role coherence@10:      65.17%
PCA role coherence@10:         63.10%
Autoencoder role coherence@10: 58.58%

In [90]:
euclidean_role_results = player_profile_df[["player_id", "role_group"]].copy()
euclidean_role_results["coherence"] = role_coherence_scores

cosine_role_results = player_profile_df[["player_id", "role_group"]].copy()
cosine_role_results["coherence"] = cosine_role_coherence_scores

pca_role_results = player_profile_df[["player_id", "role_group"]].copy()
pca_role_results["coherence"] = pca_role_coherence_scores

autoencoder_role_results = player_train_embeddings_df[["player_id", "role_group"]].copy()
autoencoder_role_results["coherence"] = autoencoder_role_coherence_scores

In [91]:
print("EUCLIDEAN")
print(euclidean_role_results.groupby("role_group")["coherence"].mean())

print("\nCOSINE")
print(cosine_role_results.groupby("role_group")["coherence"].mean())

print("\nPCA")
print(pca_role_results.groupby("role_group")["coherence"].mean())

print("\nAUTOENCODER")
print(autoencoder_role_results.groupby("role_group")["coherence"].mean())

EUCLIDEAN
role_group
Defender      0.727058
Forward       0.654083
Goalkeeper    0.957612
Midfielder    0.524413
Name: coherence, dtype: float64

COSINE
role_group
Defender      0.703116
Forward       0.671198
Goalkeeper    0.957164
Midfielder    0.504442
Name: coherence, dtype: float64

PCA
role_group
Defender      0.676976
Forward       0.650269
Goalkeeper    0.933881
Midfielder    0.490565
Name: coherence, dtype: float64

AUTOENCODER
role_group
Defender      0.635028
Forward       0.599218
Goalkeeper    0.937463
Midfielder    0.434178
Name: coherence, dtype: float64

In [92]:
match_counts = training_player_match_df.groupby("player_id")["match_id"].nunique()

stable_player_ids = match_counts[match_counts >= 20].index

print("Players with >=20 qualifying matches:", len(stable_player_ids))

Players with >=20 qualifying matches: 1633

In [93]:
split_a_parts = []
split_b_parts = []

for player_id in stable_player_ids:
    player_matches = training_player_match_df[training_player_match_df["player_id"] == player_id]
    player_matches = player_matches.sample(frac=1, random_state=42)

    midpoint = len(player_matches) // 2

    split_a_parts.append(player_matches.iloc[:midpoint])
    split_b_parts.append(player_matches.iloc[midpoint:])

split_a_df = pd.concat(split_a_parts)
split_b_df = pd.concat(split_b_parts)

print(split_a_df.shape)
print(split_b_df.shape)
print(split_a_df["player_id"].nunique())
print(split_b_df["player_id"].nunique())

(28133, 37)
(28936, 37)
1633
1633

In [94]:
split_a_profiles = split_a_df.groupby("player_id")[autoencoder_features].mean().reset_index()
split_b_profiles = split_b_df.groupby("player_id")[autoencoder_features].mean().reset_index()

print(split_a_profiles.shape)
print(split_b_profiles.shape)

(1633, 16)
(1633, 16)

In [95]:
split_a_scaled = evaluation_scaler.transform(split_a_profiles[autoencoder_features])
split_b_scaled = evaluation_scaler.transform(split_b_profiles[autoencoder_features])

euclidean_stability_knn = NearestNeighbors(n_neighbors=11, metric="euclidean")
euclidean_stability_knn.fit(evaluation_scaled_features)

_, split_a_indices = euclidean_stability_knn.kneighbors(split_a_scaled)
_, split_b_indices = euclidean_stability_knn.kneighbors(split_b_scaled)

reference_player_ids = player_profile_df["player_id"].to_numpy()

euclidean_stability_scores = []

for i in range(len(split_a_profiles)):
    target_id = split_a_profiles.iloc[i]["player_id"]

    neighbors_a = reference_player_ids[split_a_indices[i]]
    neighbors_b = reference_player_ids[split_b_indices[i]]

    neighbors_a = [player_id for player_id in neighbors_a if player_id != target_id][:10]
    neighbors_b = [player_id for player_id in neighbors_b if player_id != target_id][:10]

    set_a = set(neighbors_a)
    set_b = set(neighbors_b)

    jaccard = len(set_a & set_b) / len(set_a | set_b)
    euclidean_stability_scores.append(jaccard)

euclidean_stability = np.mean(euclidean_stability_scores)

print(f"Euclidean recommendation stability: {euclidean_stability:.2%}")

Euclidean recommendation stability: 12.46%

In [96]:
def calculate_stability(query_a, query_b, reference_features, reference_player_ids, target_player_ids, metric="euclidean", k=10):
    knn = NearestNeighbors(n_neighbors=k + 1, metric=metric)
    knn.fit(reference_features)

    _, indices_a = knn.kneighbors(query_a)
    _, indices_b = knn.kneighbors(query_b)

    stability_scores = []

    for i, target_id in enumerate(target_player_ids):
        neighbors_a = reference_player_ids[indices_a[i]]
        neighbors_b = reference_player_ids[indices_b[i]]

        neighbors_a = [player_id for player_id in neighbors_a if player_id != target_id][:k]
        neighbors_b = [player_id for player_id in neighbors_b if player_id != target_id][:k]

        set_a = set(neighbors_a)
        set_b = set(neighbors_b)

        jaccard = len(set_a & set_b) / len(set_a | set_b)
        stability_scores.append(jaccard)

    return np.mean(stability_scores)

In [97]:
target_player_ids = split_a_profiles["player_id"].to_numpy()

cosine_stability = calculate_stability(
    split_a_scaled,
    split_b_scaled,
    evaluation_scaled_features,
    reference_player_ids,
    target_player_ids,
    metric="cosine"
)

print(f"Cosine recommendation stability: {cosine_stability:.2%}")

Cosine recommendation stability: 10.90%

In [98]:
pca_reference = pca_evaluation.transform(evaluation_scaled_features)
pca_split_a = pca_evaluation.transform(split_a_scaled)
pca_split_b = pca_evaluation.transform(split_b_scaled)

pca_stability = calculate_stability(
    pca_split_a,
    pca_split_b,
    pca_reference,
    reference_player_ids,
    target_player_ids,
    metric="euclidean"
)

print(f"Euclidean recommendation stability: {euclidean_stability:.2%}")
print(f"Cosine recommendation stability:    {cosine_stability:.2%}")
print(f"PCA recommendation stability:       {pca_stability:.2%}")

Euclidean recommendation stability: 12.46%
Cosine recommendation stability:    10.90%
PCA recommendation stability:       8.60%

In [99]:
print(scaler)
print(evaluation_scaler)

StandardScaler()
StandardScaler()

In [100]:
autoencoder_scaler = StandardScaler()
autoencoder_scaler.fit(X_train)

print(autoencoder_scaler.mean_)
print(autoencoder_scaler.scale_)

[4.17428102e+01 7.47053495e+01 9.37190328e+00 2.18226832e+01
 3.30415953e+01 3.56888737e+00 1.63950851e+00 3.17174412e+01
 1.18271063e+00 1.33153761e-01 1.27888119e-01 4.98789452e-02
 3.28085589e+00 1.02301345e+00 2.72003055e+01]
[20.69325486 14.18842796  7.22926619 13.78600911 18.3611389   3.34532971
  2.29879314 40.91992926  1.71066567  0.47599837  0.29499871  0.09811853
  2.80234466  1.32522548 32.80308805]

In [101]:
print(type(X_train) if "X_train" in globals() else "X_train does not exist")

if "X_train" in globals():
    print(X_train.shape)

<class 'pandas.core.frame.DataFrame'>
(70877, 15)

In [102]:
# Scale individual player-match observations
split_a_ae_scaled = autoencoder_scaler.transform(split_a_df[autoencoder_features])
split_b_ae_scaled = autoencoder_scaler.transform(split_b_df[autoencoder_features])

# Convert to PyTorch tensors
split_a_tensor = torch.tensor(split_a_ae_scaled, dtype=torch.float32)
split_b_tensor = torch.tensor(split_b_ae_scaled, dtype=torch.float32)

# Encode each player-match observation
model.eval()

with torch.no_grad():
    split_a_match_embeddings = model.encoder(split_a_tensor).numpy()
    split_b_match_embeddings = model.encoder(split_b_tensor).numpy()

print(split_a_match_embeddings.shape)
print(split_b_match_embeddings.shape)

(28133, 5)
(28936, 5)

In [103]:
latent_columns = [f"latent_{i}" for i in range(1, 6)]

split_a_embeddings_df = pd.DataFrame(
    split_a_match_embeddings,
    columns=latent_columns
)
split_a_embeddings_df["player_id"] = split_a_df["player_id"].to_numpy()

split_b_embeddings_df = pd.DataFrame(
    split_b_match_embeddings,
    columns=latent_columns
)
split_b_embeddings_df["player_id"] = split_b_df["player_id"].to_numpy()

split_a_player_embeddings = (
    split_a_embeddings_df
    .groupby("player_id")[latent_columns]
    .mean()
    .reset_index()
)

split_b_player_embeddings = (
    split_b_embeddings_df
    .groupby("player_id")[latent_columns]
    .mean()
    .reset_index()
)

print(split_a_player_embeddings.shape)
print(split_b_player_embeddings.shape)

(1633, 6)
(1633, 6)

In [104]:
ae_reference_features = player_train_embeddings_df[latent_columns].to_numpy()
ae_reference_player_ids = player_train_embeddings_df["player_id"].to_numpy()

ae_split_a = split_a_player_embeddings[latent_columns].to_numpy()
ae_split_b = split_b_player_embeddings[latent_columns].to_numpy()

ae_target_player_ids = split_a_player_embeddings["player_id"].to_numpy()

autoencoder_stability = calculate_stability(
    ae_split_a,
    ae_split_b,
    ae_reference_features,
    ae_reference_player_ids,
    ae_target_player_ids,
    metric="euclidean"
)

print(f"Euclidean recommendation stability: {euclidean_stability:.2%}")
print(f"Cosine recommendation stability:    {cosine_stability:.2%}")
print(f"PCA recommendation stability:       {pca_stability:.2%}")
print(f"Autoencoder recommendation stability: {autoencoder_stability:.2%}")

Euclidean recommendation stability: 12.46%
Cosine recommendation stability:    10.90%
PCA recommendation stability:       8.60%
Autoencoder recommendation stability: 5.06%

In [105]:
print(training_player_match_df.columns.tolist())

['player_id', 'player_name', 'team_id', 'match_id', 'primary_position_id', 'position_event_count', 'role_group', 'total_passes', 'completed_passes', 'progressive_passes', 'pass_completion_rate', 'progressive_pass_rate', 'total_shots', 'goals', 'total_xg', 'average_xg_per_shot', 'goals_minus_xg', 'total_dribbles', 'successful_dribbles', 'dribble_success_rate', 'total_carries', 'progressive_carries', 'total_duels', 'successful_duels', 'duel_success_rate', 'matches_played', 'minutes_played', 'passes_per_90', 'progressive_passes_per_90', 'shots_per_90', 'goals_per_90', 'xg_per_90', 'dribbles_per_90', 'carries_per_90', 'progressive_carries_per_90', 'duels_per_90', 'successful_duels_per_90']

In [106]:
[name for name in globals() if "match" in name.lower()]

['match_id',
 'match_end_time',
 'problem_match_id',
 'player_match_df',
 'training_player_match_df',
 'match_counts',
 'player_matches',
 'split_a_match_embeddings',
 'split_b_match_embeddings']

In [107]:
%%sql

describe matches;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

10 rows affected.

+-------------------+------+------+-----+---------+-------+
|       Field       | Type | Null | Key | Default | Extra |
+-------------------+------+------+-----+---------+-------+
|      match_id     | int  |  NO  | PRI |   None  |       |
|     match_date    | date | YES  |     |   None  |       |
|     match_week    | int  | YES  |     |   None  |       |
|     home_score    | int  | YES  |     |   None  |       |
|     away_score    | int  | YES  |     |   None  |       |
|    home_team_id   | int  | YES  | MUL |   None  |       |
|    away_team_id   | int  | YES  | MUL |   None  |       |
|   competition_id  | int  | YES  | MUL |   None  |       |
|     season_id     | int  | YES  | MUL |   None  |       |
| competition_stage | int  | YES  |     |   None  |       |
+-------------------+------+------+-----+---------+-------+
Truncated to displaylimit of 10.

In [109]:
%%sql
    
select match_id, match_date from matches;

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

3464 rows affected.

+----------+------------+
| match_id | match_date |
+----------+------------+
|   7298   | 2018-02-24 |
|   7430   | 2018-04-15 |
|   7443   | 2018-05-05 |
|   7444   | 2018-05-06 |
|   7445   | 2018-05-06 |
|   7451   | 2018-05-13 |
|   7456   | 2018-05-20 |
|   7457   | 2018-05-24 |
|   7471   | 2018-06-30 |
|   7472   | 2018-07-01 |
+----------+------------+
Truncated to displaylimit of 10.

In [110]:
match_dates_result = %sql select match_id, match_date from matches
match_dates_df = match_dates_result.DataFrame()

match_dates_df.head()

Running query in 'mysql+pymysql://notebook_user:***@localhost:3306/football_db'

3464 rows affected.

   match_id  match_date
0      7298  2018-02-24
1      7430  2018-04-15
2      7443  2018-05-05
3      7444  2018-05-06
4      7445  2018-05-06

In [111]:
print(match_dates_df.shape)
print(match_dates_df["match_date"].isna().sum())
print(match_dates_df["match_date"].min())
print(match_dates_df["match_date"].max())

(3464, 2)
0
1958-06-24
2025-07-27

In [112]:
temporal_df = training_player_match_df.merge(match_dates_df, on="match_id", how="left")
temporal_df["match_date"] = pd.to_datetime(temporal_df["match_date"])

print(temporal_df.shape)
print("Missing dates:", temporal_df["match_date"].isna().sum())
print("Unique players:", temporal_df["player_id"].nunique())
print("Date range:", temporal_df["match_date"].min(), "to", temporal_df["match_date"].max())

(88513, 38)
Missing dates: 0
Unique players: 8488
Date range: 1958-06-24 00:00:00 to 2025-07-27 00:00:00

In [113]:
stable_temporal_df = temporal_df[temporal_df["player_id"].isin(stable_player_ids)].copy()

player_date_ranges = (stable_temporal_df.groupby("player_id")["match_date"].agg(["min", "max"]))
player_date_ranges["span_days"] = (player_date_ranges["max"] - player_date_ranges["min"]).dt.days

print(player_date_ranges["span_days"].describe())

count    1633.000000
mean     1562.846295
std      1389.077233
min       103.000000
25%       273.000000
50%      1052.000000
75%      2668.000000
max      7593.000000
Name: span_days, dtype: float64

In [114]:
temporal_early_parts = []
temporal_late_parts = []

for player_id in stable_player_ids:
    player_data = stable_temporal_df[
        stable_temporal_df["player_id"] == player_id
    ].sort_values("match_date")

    midpoint = len(player_data) // 2

    temporal_early_parts.append(player_data.iloc[:midpoint])
    temporal_late_parts.append(player_data.iloc[midpoint:])

temporal_early_df = pd.concat(temporal_early_parts)
temporal_late_df = pd.concat(temporal_late_parts)

print(temporal_early_df.shape)
print(temporal_late_df.shape)

print("Early players:", temporal_early_df["player_id"].nunique())
print("Late players:", temporal_late_df["player_id"].nunique())

print(
    "Chronology violations:",
    (
        temporal_early_df.groupby("player_id")["match_date"].max()
        >
        temporal_late_df.groupby("player_id")["match_date"].min()
    ).sum()
)

(28133, 38)
(28936, 38)
Early players: 1633
Late players: 1633
Chronology violations: 0

In [115]:
# 1. Build early and late 15D player profiles
temporal_early_profiles = temporal_early_df.groupby("player_id")[autoencoder_features].mean().reset_index()
temporal_late_profiles = temporal_late_df.groupby("player_id")[autoencoder_features].mean().reset_index()

temporal_target_ids = temporal_early_profiles["player_id"].to_numpy()

temporal_early_scaled = evaluation_scaler.transform(temporal_early_profiles[autoencoder_features])
temporal_late_scaled = evaluation_scaler.transform(temporal_late_profiles[autoencoder_features])


# 2. Euclidean
euclidean_temporal_stability = calculate_stability(temporal_early_scaled, temporal_late_scaled, evaluation_scaled_features, reference_player_ids, temporal_target_ids, metric="euclidean")


# 3. Cosine
cosine_temporal_stability = calculate_stability(temporal_early_scaled, temporal_late_scaled, evaluation_scaled_features, reference_player_ids, temporal_target_ids, metric="cosine")


# 4. PCA
temporal_early_pca = pca_evaluation.transform(temporal_early_scaled)
temporal_late_pca = pca_evaluation.transform(temporal_late_scaled)

pca_temporal_stability = calculate_stability(temporal_early_pca, temporal_late_pca, pca_reference, reference_player_ids, temporal_target_ids, metric="euclidean")


# 5. Scale individual matches for autoencoder
temporal_early_ae_scaled = autoencoder_scaler.transform(temporal_early_df[autoencoder_features])
temporal_late_ae_scaled = autoencoder_scaler.transform(temporal_late_df[autoencoder_features])

temporal_early_tensor = torch.tensor(temporal_early_ae_scaled, dtype=torch.float32)
temporal_late_tensor = torch.tensor(temporal_late_ae_scaled, dtype=torch.float32)


# 6. Encode individual matches
model.eval()

with torch.no_grad():
    temporal_early_match_embeddings = model.encoder(temporal_early_tensor).numpy()
    temporal_late_match_embeddings = model.encoder(temporal_late_tensor).numpy()


# 7. Attach player IDs and average embeddings by player
temporal_early_embeddings_df = pd.DataFrame(temporal_early_match_embeddings, columns=latent_columns)
temporal_early_embeddings_df["player_id"] = temporal_early_df["player_id"].to_numpy()

temporal_late_embeddings_df = pd.DataFrame(temporal_late_match_embeddings, columns=latent_columns)
temporal_late_embeddings_df["player_id"] = temporal_late_df["player_id"].to_numpy()

temporal_early_player_embeddings = temporal_early_embeddings_df.groupby("player_id")[latent_columns].mean().reset_index()
temporal_late_player_embeddings = temporal_late_embeddings_df.groupby("player_id")[latent_columns].mean().reset_index()


# 8. Autoencoder
autoencoder_temporal_stability = calculate_stability(temporal_early_player_embeddings[latent_columns].to_numpy(), temporal_late_player_embeddings[latent_columns].to_numpy(), ae_reference_features, ae_reference_player_ids, temporal_early_player_embeddings["player_id"].to_numpy(), metric="euclidean")


# 9. Results
print("TEMPORAL STABILITY@10")
print("---------------------------------------")
print(f"Euclidean:   {euclidean_temporal_stability:.2%}")
print(f"Cosine:      {cosine_temporal_stability:.2%}")
print(f"PCA:         {pca_temporal_stability:.2%}")
print(f"Autoencoder: {autoencoder_temporal_stability:.2%}")

TEMPORAL STABILITY@10
---------------------------------------
Euclidean:   8.62%
Cosine:      7.58%
PCA:         5.88%
Autoencoder: 3.81%

In [116]:
reliable_match_counts = training_player_match_df.groupby("player_id")["match_id"].nunique().reset_index(name="qualifying_matches")
reliable_player_ids = reliable_match_counts[reliable_match_counts["qualifying_matches"] >= 20]["player_id"]
scouting_profiles_df = player_profile_df[player_profile_df["player_id"].isin(reliable_player_ids)].copy()
scouting_profiles_df = scouting_profiles_df.merge(reliable_match_counts, on="player_id", how="left")

print(scouting_profiles_df.shape)
print(scouting_profiles_df["role_group"].value_counts())

(1633, 19)
role_group
Defender      587
Midfielder    521
Forward       401
Goalkeeper    124
Name: count, dtype: int64

In [117]:
scouting_scaler = StandardScaler()
scouting_scaled_features = scouting_scaler.fit_transform(scouting_profiles_df[autoencoder_features])

scouting_knn = NearestNeighbors(metric="euclidean")
scouting_knn.fit(scouting_scaled_features)

NearestNeighbors(metric='euclidean')

In [118]:
def find_similar_players(player_id, top_n=10, same_role=True):
    if player_id not in scouting_profiles_df["player_id"].values:
        raise ValueError("Player is not in the reliable scouting population.")

    target_idx = scouting_profiles_df.index[scouting_profiles_df["player_id"] == player_id][0]
    target_position = scouting_profiles_df.index.get_loc(target_idx)
    target = scouting_profiles_df.loc[target_idx]
    target_vector = scouting_scaled_features[target_position]

    candidates = scouting_profiles_df.copy()
    candidate_vectors = scouting_scaled_features.copy()

    if same_role:
        role_mask = candidates["role_group"].eq(target["role_group"]).to_numpy()
        candidates = candidates[role_mask].copy()
        candidate_vectors = candidate_vectors[role_mask]

    candidates["distance"] = np.linalg.norm(candidate_vectors - target_vector, axis=1)
    candidates = candidates[candidates["player_id"] != player_id].copy()
    candidates = candidates.sort_values("distance").head(top_n)

    return candidates[["player_id", "player_name", "role_group", "qualifying_matches", "distance"]].reset_index(drop=True)

In [119]:
xavi_recommendations = find_similar_players(20131)
xavi_recommendations

,player_id,player_name,role_group,qualifying_matches,distance
0,4325,Thiago Motta,Midfielder,40,2.832373
1,3478,Francesc Fàbregas i Soler,Midfielder,113,2.843885
2,10287,İlkay Gündoğan,Midfielder,37,2.852052
3,3500,Granit Xhaka,Midfielder,78,3.120312
4,5208,Thiago Alcântara do Nascimento,Midfielder,73,3.151279
5,11392,Arthur Henrique Ramos de Oliveira Melo,Midfielder,35,3.220712
6,5216,Andrés Iniesta Luján,Midfielder,317,3.313238
7,7025,Marek Hamšík,Midfielder,41,3.353681
8,7024,Jorge Luiz Frello Filho,Midfielder,45,3.379563
9,3166,Marco Verratti,Midfielder,63,3.464458

In [120]:
def explain_similarity(target_player_id, candidate_player_id, top_n=5):
    target_idx = scouting_profiles_df.index[scouting_profiles_df["player_id"] == target_player_id][0]
    candidate_idx = scouting_profiles_df.index[scouting_profiles_df["player_id"] == candidate_player_id][0]

    target_position = scouting_profiles_df.index.get_loc(target_idx)
    candidate_position = scouting_profiles_df.index.get_loc(candidate_idx)

    target_vector = scouting_scaled_features[target_position]
    candidate_vector = scouting_scaled_features[candidate_position]

    differences = np.abs(target_vector - candidate_vector)

    comparison = pd.DataFrame({
        "feature": autoencoder_features,
        "target_value": scouting_profiles_df.loc[target_idx, autoencoder_features].to_numpy(),
        "candidate_value": scouting_profiles_df.loc[candidate_idx, autoencoder_features].to_numpy(),
        "standardized_difference": differences
    })

    comparison = comparison.sort_values("standardized_difference")

    return comparison.head(top_n), comparison.tail(top_n).sort_values("standardized_difference", ascending=False)

In [121]:
most_similar, most_different = explain_similarity(20131, 4325)

print("MOST SIMILAR FEATURES")
display(most_similar)

print("LARGEST DIFFERENCES")
display(most_different)

MOST SIMILAR FEATURES

,feature,target_value,candidate_value,standardized_difference
11,average_xg_per_shot,0.055458,0.0585,0.072912
3,progressive_pass_rate,24.299721,22.577,0.163459
2,progressive_passes_per_90,24.73606,23.641206,0.209283
10,xg_per_90,0.106563,0.076562,0.210842
14,duel_success_rate,38.658685,35.68025,0.220888

LARGEST DIFFERENCES

,feature,target_value,candidate_value,standardized_difference
12,duels_per_90,1.68231,3.948108,1.404592
5,progressive_carries_per_90,6.827732,4.267915,1.327639
7,dribble_success_rate,59.498287,38.33325,1.306972
13,successful_duels_per_90,0.87347,1.52156,1.102274
8,shots_per_90,1.357238,0.756266,0.603854

In [123]:
player_positions_df = training_player_match_df[["player_id", "primary_position_id"]].drop_duplicates("player_id")
scouting_profiles_df = scouting_profiles_df.merge(player_positions_df, on="player_id", how="left")

In [124]:
print(scouting_profiles_df["primary_position_id"].isna().sum())
print(scouting_profiles_df.shape)

0
(1633, 20)

In [125]:
scouting_profiles_df.groupby(["primary_position_id", "role_group"]).size().sort_values(ascending=False)

primary_position_id  role_group
3                    Defender      147
2                    Defender      146
5                    Defender      145
23                   Forward       141
6                    Defender      125
1                    Goalkeeper    124
21                   Forward       104
17                   Forward        96
11                   Midfielder     84
19                   Midfielder     78
9                    Midfielder     77
13                   Midfielder     72
15                   Midfielder     70
10                   Midfielder     63
16                   Midfielder     40
12                   Midfielder     33
22                   Forward        31
24                   Forward        29
7                    Defender        9
8                    Defender        8
4                    Defender        7
20                   Midfielder      2
18                   Midfielder      2
dtype: int64

In [126]:
def find_similar_players(player_id, top_n=10, position_filter="role"):
    if player_id not in scouting_profiles_df["player_id"].values:
        raise ValueError("Player is not in the reliable scouting population.")

    if position_filter not in ["role", "position", None]:
        raise ValueError("position_filter must be 'role', 'position', or None.")

    target_idx = scouting_profiles_df.index[scouting_profiles_df["player_id"] == player_id][0]
    target_position = scouting_profiles_df.index.get_loc(target_idx)
    target = scouting_profiles_df.loc[target_idx]
    target_vector = scouting_scaled_features[target_position]

    candidates = scouting_profiles_df.copy()
    candidate_vectors = scouting_scaled_features.copy()

    if position_filter == "role":
        mask = candidates["role_group"].eq(target["role_group"]).to_numpy()
        candidates = candidates[mask].copy()
        candidate_vectors = candidate_vectors[mask]

    elif position_filter == "position":
        mask = candidates["primary_position_id"].eq(target["primary_position_id"]).to_numpy()
        candidates = candidates[mask].copy()
        candidate_vectors = candidate_vectors[mask]

    candidates["distance"] = np.linalg.norm(candidate_vectors - target_vector, axis=1)
    candidates = candidates[candidates["player_id"] != player_id].copy()
    candidates = candidates.sort_values("distance").head(top_n)

    return candidates[["player_id", "player_name", "role_group", "primary_position_id", "qualifying_matches", "distance"]].reset_index(drop=True)

In [127]:
xavi_role = find_similar_players(20131, position_filter="role")
xavi_position = find_similar_players(20131, position_filter="position")
xavi_unrestricted = find_similar_players(20131, position_filter=None)

In [128]:
print("SAME ROLE")
display(xavi_role)

print("SAME POSITION")
display(xavi_position)

print("UNRESTRICTED")
display(xavi_unrestricted)

SAME ROLE

,player_id,player_name,role_group,primary_position_id,qualifying_matches,distance
0,4325,Thiago Motta,Midfielder,10,40,2.832373
1,3478,Francesc Fàbregas i Soler,Midfielder,15,113,2.843885
2,10287,İlkay Gündoğan,Midfielder,13,37,2.852052
3,3500,Granit Xhaka,Midfielder,11,78,3.120312
4,5208,Thiago Alcântara do Nascimento,Midfielder,15,73,3.151279
5,11392,Arthur Henrique Ramos de Oliveira Melo,Midfielder,15,35,3.220712
6,5216,Andrés Iniesta Luján,Midfielder,15,317,3.313238
7,7025,Marek Hamšík,Midfielder,15,41,3.353681
8,7024,Jorge Luiz Frello Filho,Midfielder,10,45,3.379563
9,3166,Marco Verratti,Midfielder,10,63,3.464458

SAME POSITION

,player_id,player_name,role_group,primary_position_id,qualifying_matches,distance
0,10287,İlkay Gündoğan,Midfielder,13,37,2.852052
1,5463,Luka Modrić,Midfielder,13,69,3.497110
2,8118,Frenkie de Jong,Midfielder,13,65,3.567317
3,6947,Miralem Pjanić,Midfielder,13,43,3.959190
4,3118,Jordan Ferri,Midfielder,13,36,4.010695
5,5470,Ivan Rakitić,Midfielder,13,196,4.388408
6,3026,Adrien Rabiot,Midfielder,13,37,4.917494
7,3211,Florent Balmont,Midfielder,13,26,4.989467
8,6998,Rafael Alcântara do Nascimento,Midfielder,13,36,5.798084
9,6595,Daniel Parejo Muñoz,Midfielder,13,48,5.828954

UNRESTRICTED

,player_id,player_name,role_group,primary_position_id,qualifying_matches,distance
0,4325,Thiago Motta,Midfielder,10,40,2.832373
1,3478,Francesc Fàbregas i Soler,Midfielder,15,113,2.843885
2,10287,İlkay Gündoğan,Midfielder,13,37,2.852052
3,3500,Granit Xhaka,Midfielder,11,78,3.120312
4,5208,Thiago Alcântara do Nascimento,Midfielder,15,73,3.151279
5,11392,Arthur Henrique Ramos de Oliveira Melo,Midfielder,15,35,3.220712
6,10252,Alex Greenwood,Defender,5,39,3.283315
7,5579,Joshua Kimmich,Defender,3,35,3.289552
8,5216,Andrés Iniesta Luján,Midfielder,15,317,3.313238
9,7025,Marek Hamšík,Midfielder,15,41,3.353681

In [129]:
def scout_replacements(player_id, top_n=10, position_filter="role", explanation_features=3):
    recommendations = find_similar_players(player_id, top_n=top_n, position_filter=position_filter).copy()
    results = []

    for _, candidate in recommendations.iterrows():
        similar, different = explain_similarity(player_id, candidate["player_id"], top_n=explanation_features)

        results.append({
            "player_id": int(candidate["player_id"]),
            "player_name": candidate["player_name"],
            "role_group": candidate["role_group"],
            "primary_position_id": int(candidate["primary_position_id"]),
            "qualifying_matches": int(candidate["qualifying_matches"]),
            "distance": round(float(candidate["distance"]), 3),
            "most_similar_features": similar["feature"].tolist(),
            "largest_differences": different["feature"].tolist()
        })

    return results

In [130]:
xavi_scouting_results = scout_replacements(20131, top_n=5, position_filter="role")
xavi_scouting_results

[{'player_id': 4325,
  'player_name': 'Thiago Motta',
  'role_group': 'Midfielder',
  'primary_position_id': 10,
  'qualifying_matches': 40,
  'distance': 2.832,
  'most_similar_features': ['average_xg_per_shot',
   'progressive_pass_rate',
   'progressive_passes_per_90'],
  'largest_differences': ['duels_per_90',
   'progressive_carries_per_90',
   'dribble_success_rate']},
 {'player_id': 3478,
  'player_name': 'Francesc Fàbregas i Soler',
  'role_group': 'Midfielder',
  'primary_position_id': 15,
  'qualifying_matches': 113,
  'distance': 2.844,
  'most_similar_features': ['dribbles_per_90',
   'duel_success_rate',
   'progressive_pass_rate'],
  'largest_differences': ['duels_per_90',
   'carries_per_90',
   'successful_duels_per_90']},
 {'player_id': 10287,
  'player_name': 'İlkay Gündoğan',
  'role_group': 'Midfielder',
  'primary_position_id': 13,
  'qualifying_matches': 37,
  'distance': 2.852,
  'most_similar_features': ['duel_success_rate',
   'goals_per_90',
   'dribbles_per_90'],
  'largest_differences': ['passes_per_90',
   'carries_per_90',
   'progressive_passes_per_90']},
 {'player_id': 3500,
  'player_name': 'Granit Xhaka',
  'role_group': 'Midfielder',
  'primary_position_id': 11,
  'qualifying_matches': 78,
  'distance': 3.12,
  'most_similar_features': ['pass_completion_rate',
   'shots_per_90',
   'progressive_pass_rate'],
  'largest_differences': ['dribble_success_rate',
   'carries_per_90',
   'progressive_carries_per_90']},
 {'player_id': 5208,
  'player_name': 'Thiago Alcântara do Nascimento',
  'role_group': 'Midfielder',
  'primary_position_id': 15,
  'qualifying_matches': 73,
  'distance': 3.151,
  'most_similar_features': ['shots_per_90',
   'pass_completion_rate',
   'average_xg_per_shot'],
  'largest_differences': ['successful_duels_per_90',
   'duels_per_90',
   'progressive_passes_per_90']}]

In [131]:
player_match_df.columns.tolist()

['player_id',
 'player_name',
 'team_id',
 'match_id',
 'primary_position_id',
 'position_event_count',
 'role_group',
 'total_passes',
 'completed_passes',
 'progressive_passes',
 'pass_completion_rate',
 'progressive_pass_rate',
 'total_shots',
 'goals',
 'total_xg',
 'average_xg_per_shot',
 'goals_minus_xg',
 'total_dribbles',
 'successful_dribbles',
 'dribble_success_rate',
 'total_carries',
 'progressive_carries',
 'total_duels',
 'successful_duels',
 'duel_success_rate',
 'matches_played',
 'minutes_played',
 'passes_per_90',
 'progressive_passes_per_90',
 'shots_per_90',
 'goals_per_90',
 'xg_per_90',
 'dribbles_per_90',
 'carries_per_90',
 'progressive_carries_per_90',
 'duels_per_90',
 'successful_duels_per_90']